import { z } from "zod";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";

const schema=z.object({businessHeadId:z.uuid(),requisitionId:z.uuid().nullable().optional(),fullName:z.string().min(2).max(160),email:z.email().nullable().optional(),phone:z.string().max(30).nullable().optional(),position:z.string().min(2).max(120),departmentId:z.uuid().nullable().optional(),source:z.string().max(80).nullable().optional(),consented:z.boolean().default(false)});

export async function GET(request:Request){try{const u=new URL(request.url);const head=u.searchParams.get('businessHeadId');const stage=u.searchParams.get('stage');const user=await requireApiUser('recruitment:read',head);if(user instanceof Response)return user;return ok(await db()`SELECT c.*,b.name AS business_head,d.name AS department,r.requisition_code FROM candidates c JOIN business_heads b ON b.id=c.business_head_id LEFT JOIN departments d ON d.id=c.department_id LEFT JOIN job_requisitions r ON r.id=c.requisition_id WHERE (${head}::uuid IS NULL OR c.business_head_id=${head}::uuid) AND (${stage}::text IS NULL OR c.stage=${stage}) ORDER BY c.updated_at DESC LIMIT 500`);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const user=await requireApiUser('recruitment:write',input.businessHeadId);if(user instanceof Response)return user;const sql=db();const [row]=await sql.begin(async tx=>{const rows=await tx`INSERT INTO candidates (business_head_id,requisition_id,full_name,email,phone,position,department_id,source,owner_id,consented_at) VALUES (${input.businessHeadId},${input.requisitionId||null},${input.fullName},${input.email||null},${input.phone||null},${input.position},${input.departmentId||null},${input.source||null},${user.id},${input.consented?new Date():null}) RETURNING *`;await tx`INSERT INTO candidate_stage_events (candidate_id,to_stage,notes,changed_by) VALUES (${rows[0].id},'applied','Candidate added',${user.id})`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'candidate.create','candidate',${rows[0].id},${input.businessHeadId},${JSON.stringify(rows[0])}::jsonb,'Candidate added')`;return rows;});return ok(row,{status:201});}catch(e){return apiError(e);}}
