import { z } from "zod";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";

const schema=z.object({businessHeadId:z.uuid().nullable().optional(),departmentId:z.uuid().nullable().optional(),name:z.string().min(3).max(120),startDate:z.iso.date(),endDate:z.iso.date(),template:z.object({ratingScale:z.array(z.object({value:z.number(),label:z.string()})).min(2),sections:z.array(z.object({code:z.string(),name:z.string(),weight:z.number().min(0).max(100)})).min(1)}),}).refine(v=>v.endDate>=v.startDate,{message:'End date must not precede start date'}).refine(v=>Math.abs(v.template.sections.reduce((s,x)=>s+x.weight,0)-100)<0.01,{message:'Section weights must total 100'});

export async function GET(request:Request){try{const params=new URL(request.url).searchParams;const head=params.get('businessHeadId');const department=params.get('departmentId');const user=await requireApiUser('performance:read',head,department);if(user instanceof Response)return user;return ok(await db()`SELECT c.*,b.name AS business_head,d.name AS department,(SELECT count(*)::int FROM performance_reviews r WHERE r.cycle_id=c.id) AS review_count,(SELECT count(*)::int FROM performance_reviews r WHERE r.cycle_id=c.id AND r.status='completed') AS completed_count FROM performance_cycles c LEFT JOIN business_heads b ON b.id=c.business_head_id LEFT JOIN departments d ON d.id=c.department_id WHERE (${head}::uuid IS NULL OR c.business_head_id=${head}::uuid OR c.business_head_id IS NULL) AND (${department}::uuid IS NULL OR c.department_id=${department}::uuid) ORDER BY c.start_date DESC`);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const user=await requireApiUser('performance:write',input.businessHeadId,input.departmentId);if(user instanceof Response)return user;const sql=db();const [row]=await sql.begin(async tx=>{const rows=await tx`INSERT INTO performance_cycles (business_head_id,department_id,name,start_date,end_date,template) VALUES (${input.businessHeadId||null},${input.departmentId||null},${input.name},${input.startDate},${input.endDate},${JSON.stringify(input.template)}::jsonb) RETURNING *`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'performance_cycle.create','performance_cycle',${rows[0].id},${input.businessHeadId||null},${JSON.stringify(rows[0])}::jsonb,'Performance cycle created')`;return rows;});return ok(row,{status:201});}catch(e){return apiError(e);}}
