import { z } from "zod";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";

const schema=z.object({cycleId:z.uuid(),employeeId:z.uuid(),reviewerId:z.uuid(),reviewType:z.enum(['self','manager','second_level','peer','direct_report','360']),ratings:z.record(z.string(),z.number().min(0).max(10)),overallRating:z.number().min(0).max(10).nullable().optional(),comments:z.string().max(5000).nullable().optional(),submit:z.boolean().default(false)});

export async function GET(request:Request){try{const u=new URL(request.url);const cycle=u.searchParams.get('cycleId');const employee=u.searchParams.get('employeeId');const head=u.searchParams.get('businessHeadId');const department=u.searchParams.get('departmentId');const user=await requireApiUser('performance:read',head,department);if(user instanceof Response)return user;return ok(await db()`SELECT r.*,concat_ws(' ',e.first_name,e.last_name) AS employee_name,concat_ws(' ',rv.first_name,rv.last_name) AS reviewer_name,e.business_head_id,e.department_id FROM performance_reviews r JOIN employees e ON e.id=r.employee_id JOIN employees rv ON rv.id=r.reviewer_id WHERE (${cycle}::uuid IS NULL OR r.cycle_id=${cycle}::uuid) AND (${employee}::uuid IS NULL OR r.employee_id=${employee}::uuid) AND (${head}::uuid IS NULL OR e.business_head_id=${head}::uuid) AND (${department}::uuid IS NULL OR e.department_id=${department}::uuid) ORDER BY r.submitted_at DESC NULLS FIRST`);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const sql=db();const [employee]=await sql<{business_head_id:string;department_id:string|null}[]>`SELECT business_head_id,department_id FROM employees WHERE id=${input.employeeId}`;const user=await requireApiUser('performance:write',employee?.business_head_id,employee?.department_id);if(user instanceof Response)return user;const [row]=await sql.begin(async tx=>{const rows=await tx`INSERT INTO performance_reviews (cycle_id,employee_id,reviewer_id,review_type,ratings,overall_rating,comments,status,submitted_at) VALUES (${input.cycleId},${input.employeeId},${input.reviewerId},${input.reviewType},${JSON.stringify(input.ratings)}::jsonb,${input.overallRating??null},${input.comments||null},${input.submit?'completed':'draft'},${input.submit?new Date():null}) ON CONFLICT (cycle_id,employee_id,reviewer_id,review_type) DO UPDATE SET ratings=EXCLUDED.ratings,overall_rating=EXCLUDED.overall_rating,comments=EXCLUDED.comments,status=EXCLUDED.status,submitted_at=EXCLUDED.submitted_at RETURNING *`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},${input.submit?'performance_review.submit':'performance_review.save'},'performance_review',${rows[0].id},${employee.business_head_id},${JSON.stringify(rows[0])}::jsonb,${input.submit?'Review submitted':'Review draft saved'})`;return rows;});return ok(row);}catch(e){return apiError(e);}}
