import { z } from "zod";
import { db } from "@/lib/database";
import { apiError, fail, ok, requireApiUser } from "@/lib/api";
import { hasRoleForScope } from "@/lib/auth";

const upsertSchema=z.object({employeeId:z.uuid(),attendanceDate:z.iso.date(),status:z.enum(['present','absent','half_day','paid_leave','unpaid_leave','weekly_off','holiday','work_from_home','on_duty','not_employed']),firstIn:z.iso.datetime().nullable().optional(),lastOut:z.iso.datetime().nullable().optional(),workedMinutes:z.number().int().min(0).max(1440).default(0),overtimeMinutes:z.number().int().min(0).max(1440).default(0),remarks:z.string().max(500).optional()});

export async function GET(request:Request){try{const u=new URL(request.url);const date=u.searchParams.get('date')||new Date().toISOString().slice(0,10);const head=u.searchParams.get('businessHeadId');const department=u.searchParams.get('departmentId');const location=u.searchParams.get('locationId');const shift=u.searchParams.get('shiftId');const manager=u.searchParams.get('managerId');const employeeId=u.searchParams.get('employeeId');const user=await requireApiUser('attendance:read',head,department);if(user instanceof Response)return user;const broad=hasRoleForScope(user,['HR_ADMIN','HR_OPERATIONS','PAYROLL_ADMIN','AUDITOR'],head,department);const actorEmployees=broad?[]:await db()< {id:string}[]>`SELECT id FROM employees WHERE user_id=${user.id}`;const actorEmployee=actorEmployees[0];const rows=await db()`SELECT a.id,e.id AS employee_id,e.employee_code,e.first_name,e.last_name,e.position,e.business_head_id,e.department_id,e.work_location_id,b.name AS business_head,d.name AS department,w.name AS work_location,s.id AS shift_id,s.name AS shift,a.first_in,a.last_out,a.worked_minutes,a.late_minutes,a.early_minutes,a.overtime_minutes,a.remarks,a.locked_at,coalesce(a.status::text,CASE WHEN e.date_joined>${date}::date OR (e.last_working_date IS NOT NULL AND e.last_working_date<${date}::date) THEN 'not_employed' ELSE 'missing' END) AS status FROM employees e JOIN business_heads b ON b.id=e.business_head_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN work_locations w ON w.id=e.work_location_id LEFT JOIN shift_rosters sr ON sr.employee_id=e.id AND sr.roster_date=${date}::date LEFT JOIN shifts s ON s.id=sr.shift_id LEFT JOIN attendance_days a ON a.employee_id=e.id AND a.attendance_date=${date}::date WHERE e.status NOT IN ('candidate','preboarding','archived') AND (${head}::uuid IS NULL OR e.business_head_id=${head}::uuid) AND (${department}::uuid IS NULL OR e.department_id=${department}::uuid) AND (${location}::uuid IS NULL OR e.work_location_id=${location}::uuid) AND (${shift}::uuid IS NULL OR sr.shift_id=${shift}::uuid) AND (${manager}::uuid IS NULL OR e.reporting_manager_id=${manager}::uuid) AND (${employeeId}::uuid IS NULL OR e.id=${employeeId}::uuid) AND (${broad} OR e.id=${actorEmployee?.id||null}::uuid OR e.reporting_manager_id=${actorEmployee?.id||null}::uuid) ORDER BY e.first_name,e.last_name`;return ok(rows);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=upsertSchema.parse(await request.json());const sql=db();const [employee]=await sql<{business_head_id:string;department_id:string|null}[]>`SELECT business_head_id,department_id FROM employees WHERE id=${input.employeeId}`;if(!employee)return fail('Employee not found',404);const user=await requireApiUser('attendance:write',employee.business_head_id,employee.department_id);if(user instanceof Response)return user;const [month]=await sql<{status:string}[]>`SELECT status FROM attendance_months WHERE business_head_id=${employee.business_head_id} AND period_month=date_trunc('month',${input.attendanceDate}::date)::date`;if(month&&month.status!=='open')return fail(month.status==='locked'?'Attendance is locked for this month; submit a correction request':'Attendance is under review for this company. Choose the company, then use "Return month to open" on the Attendance screen before editing',409);const result=await sql.begin(async tx=>{const previous=await tx`SELECT * FROM attendance_days WHERE employee_id=${input.employeeId} AND attendance_date=${input.attendanceDate} FOR UPDATE`;if(previous[0]?.locked_at)return null;const rows=await tx`INSERT INTO attendance_days (employee_id,attendance_date,status,first_in,last_out,worked_minutes,overtime_minutes,remarks,source) VALUES (${input.employeeId},${input.attendanceDate},${input.status},${input.firstIn||null},${input.lastOut||null},${input.workedMinutes},${input.overtimeMinutes},${input.remarks||null},'hrms') ON CONFLICT (employee_id,attendance_date) DO UPDATE SET status=EXCLUDED.status,first_in=EXCLUDED.first_in,last_out=EXCLUDED.last_out,worked_minutes=EXCLUDED.worked_minutes,overtime_minutes=EXCLUDED.overtime_minutes,remarks=EXCLUDED.remarks,version=attendance_days.version+1 WHERE attendance_days.locked_at IS NULL RETURNING *`;if(!rows[0])return null;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,before_data,after_data,reason) VALUES (${user.id},'attendance.upsert','attendance_day',${rows[0].id},${employee.business_head_id},${previous[0]?JSON.stringify(previous[0]):null}::jsonb,${JSON.stringify(rows[0])}::jsonb,${input.remarks||'Attendance updated'})`;return rows[0];});if(!result)return fail('Attendance is locked for this day',409);return ok(result);}catch(e){return apiError(e);}}
