import { z } from "zod";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";

const schema=z.object({requisitionCode:z.string().min(3).max(30),businessHeadId:z.uuid(),departmentId:z.uuid().nullable().optional(),position:z.string().min(2).max(120),openings:z.number().int().min(1).max(100).default(1),employmentType:z.string().max(40).default('permanent'),budgetMin:z.number().nonnegative().nullable().optional(),budgetMax:z.number().nonnegative().nullable().optional(),reason:z.string().min(5).max(1000),targetDate:z.iso.date().nullable().optional()}).refine(v=>v.budgetMin==null||v.budgetMax==null||v.budgetMax>=v.budgetMin,{message:'Maximum budget must be at least the minimum budget'});

export async function GET(request:Request){try{const u=new URL(request.url);const head=u.searchParams.get('businessHeadId');const user=await requireApiUser('recruitment:read',head);if(user instanceof Response)return user;return ok(await db()`SELECT r.*,b.name AS business_head,d.name AS department,(SELECT count(*)::int FROM candidates c WHERE c.requisition_id=r.id) AS candidates FROM job_requisitions r JOIN business_heads b ON b.id=r.business_head_id LEFT JOIN departments d ON d.id=r.department_id WHERE (${head}::uuid IS NULL OR r.business_head_id=${head}::uuid) ORDER BY r.created_at DESC`);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const user=await requireApiUser('recruitment:write',input.businessHeadId);if(user instanceof Response)return user;const sql=db();const [row]=await sql.begin(async tx=>{const rows=await tx`INSERT INTO job_requisitions (requisition_code,business_head_id,department_id,position,openings,employment_type,budget_min,budget_max,reason,target_date,created_by) VALUES (${input.requisitionCode},${input.businessHeadId},${input.departmentId||null},${input.position},${input.openings},${input.employmentType},${input.budgetMin??null},${input.budgetMax??null},${input.reason},${input.targetDate||null},${user.id}) RETURNING *`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'requisition.create','job_requisition',${rows[0].id},${input.businessHeadId},${JSON.stringify(rows[0])}::jsonb,${input.reason})`;return rows;});return ok(row,{status:201});}catch(e){return apiError(e);}}
