import { z } from "zod";
import { apiError, fail, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";
import { sealJson } from "@/lib/encryption";

const base=z.object({businessHeadId:z.uuid()});
const schema=z.discriminatedUnion('kind',[
  base.extend({kind:z.literal('legal_entity'),name:z.string().min(2).max(160),legalName:z.string().min(2).max(240),countryCode:z.string().length(2).default('IN'),taxIdentifier:z.string().min(3).max(120).nullable().optional()}),
  base.extend({kind:z.literal('work_location'),code:z.string().min(2).max(30),name:z.string().min(2).max(160),timezone:z.string().min(3).max(80).default('Asia/Kolkata'),address:z.record(z.string(),z.string()).default({})}),
  base.extend({kind:z.literal('department'),code:z.string().min(2).max(30),name:z.string().min(2).max(160)}),
  base.extend({kind:z.literal('cost_centre'),code:z.string().min(2).max(30),name:z.string().min(2).max(160),departmentId:z.uuid().nullable().optional()}),
  base.extend({kind:z.literal('job_position'),code:z.string().min(2).max(30),title:z.string().min(2).max(160),departmentId:z.uuid().nullable().optional(),grade:z.string().max(40).nullable().optional(),reportsToPositionId:z.uuid().nullable().optional()}),
]);

export async function GET(request:Request){try{const head=new URL(request.url).searchParams.get('businessHeadId');const user=await requireApiUser('people:read',head);if(user instanceof Response)return user;const sql=db();const [legalEntities,locations,costCentres,positions,departments]=await Promise.all([sql`SELECT id,business_head_id,name,legal_name,country_code,active,(tax_identifier_encrypted IS NOT NULL) AS has_tax_identifier FROM legal_entities WHERE (${head}::uuid IS NULL OR business_head_id=${head}::uuid) ORDER BY name`,sql`SELECT * FROM work_locations WHERE (${head}::uuid IS NULL OR business_head_id=${head}::uuid) ORDER BY name`,sql`SELECT c.*,d.name AS department FROM cost_centres c LEFT JOIN departments d ON d.id=c.department_id WHERE (${head}::uuid IS NULL OR c.business_head_id=${head}::uuid) ORDER BY c.name`,sql`SELECT p.*,d.name AS department,parent.title AS reports_to_title FROM job_positions p LEFT JOIN departments d ON d.id=p.department_id LEFT JOIN job_positions parent ON parent.id=p.reports_to_position_id WHERE (${head}::uuid IS NULL OR p.business_head_id=${head}::uuid) ORDER BY p.title`,sql`SELECT d.*,b.name AS business_head_name FROM departments d JOIN business_heads b ON b.id=d.business_head_id WHERE (${head}::uuid IS NULL OR d.business_head_id=${head}::uuid) ORDER BY d.name,b.name`]);return ok({legalEntities,locations,costCentres,positions,departments});}catch(error){return apiError(error);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const user=await requireApiUser('people:write',input.businessHeadId,'departmentId' in input?input.departmentId:null);if(user instanceof Response)return user;const sql=db();if('departmentId' in input&&input.departmentId){const [department]=await sql`SELECT id FROM departments WHERE id=${input.departmentId} AND business_head_id=${input.businessHeadId}`;if(!department)return fail('Department does not belong to the selected business head',422);}const [created]=await sql.begin(async tx=>{let rows;if(input.kind==='legal_entity')rows=await tx`INSERT INTO legal_entities (business_head_id,name,legal_name,country_code,tax_identifier_encrypted) VALUES (${input.businessHeadId},${input.name},${input.legalName},${input.countryCode.toUpperCase()},${input.taxIdentifier?sealJson({value:input.taxIdentifier}):null}) RETURNING id,business_head_id,name,legal_name,country_code,active`;else if(input.kind==='work_location')rows=await tx`INSERT INTO work_locations (business_head_id,code,name,timezone,address) VALUES (${input.businessHeadId},${input.code},${input.name},${input.timezone},${JSON.stringify(input.address)}::jsonb) RETURNING *`;else if(input.kind==='department')rows=await tx`INSERT INTO departments (business_head_id,code,name) VALUES (${input.businessHeadId},${input.code},${input.name}) RETURNING *`;else if(input.kind==='cost_centre')rows=await tx`INSERT INTO cost_centres (business_head_id,code,name,department_id) VALUES (${input.businessHeadId},${input.code},${input.name},${input.departmentId||null}) RETURNING *`;else rows=await tx`INSERT INTO job_positions (business_head_id,department_id,code,title,grade,reports_to_position_id) VALUES (${input.businessHeadId},${input.departmentId||null},${input.code},${input.title},${input.grade||null},${input.reportsToPositionId||null}) RETURNING *`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},${`organisation.${input.kind}.create`},${input.kind},${rows[0].id},${input.businessHeadId},${JSON.stringify({...rows[0],hasTaxIdentifier:input.kind==='legal_entity'?Boolean(input.taxIdentifier):undefined})}::jsonb,'Organisation master created')`;return rows;});return ok(created,{status:201});}catch(error){return apiError(error);}}
