import { z } from "zod";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";

const question=z.object({code:z.string().regex(/^[a-z][a-z0-9_]{1,39}$/),prompt:z.string().min(3).max(500),type:z.enum(['rating','single_choice','multi_choice','text']),required:z.boolean().default(true),options:z.array(z.string().min(1).max(160)).max(20).optional()}).strict().refine(item=>!['single_choice','multi_choice'].includes(item.type)||Boolean(item.options?.length),{message:'Choice questions require options'});
const schema=z.object({businessHeadId:z.uuid().nullable().optional(),title:z.string().min(3).max(200),description:z.string().max(2000).nullable().optional(),surveyType:z.enum(['pulse','engagement','onboarding','exit','custom']).default('pulse'),anonymous:z.boolean().default(false),questions:z.array(question).min(1).max(100),opensAt:z.iso.datetime(),closesAt:z.iso.datetime()}).refine(value=>value.closesAt>value.opensAt,{message:'Survey close must follow open'});

export async function GET(request:Request){try{const head=new URL(request.url).searchParams.get('businessHeadId');const actor=await requireApiUser('performance:read',head);if(actor instanceof Response)return actor;return ok(await db()`SELECT s.id,s.business_head_id,s.title,s.description,s.survey_type,s.anonymous,s.questions,s.opens_at,s.closes_at,s.status,s.created_by,s.approved_by,s.decision_reason,s.created_at,b.name AS business_head,cu.full_name AS created_by_name,au.full_name AS approved_by_name,count(r.id)::int AS response_count FROM surveys s LEFT JOIN business_heads b ON b.id=s.business_head_id JOIN users cu ON cu.id=s.created_by LEFT JOIN users au ON au.id=s.approved_by LEFT JOIN survey_responses r ON r.survey_id=s.id WHERE (${head}::uuid IS NULL OR s.business_head_id=${head}::uuid OR s.business_head_id IS NULL) GROUP BY s.id,b.name,cu.full_name,au.full_name ORDER BY s.opens_at DESC`);}catch(error){return apiError(error);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const actor=await requireApiUser('performance:write',input.businessHeadId);if(actor instanceof Response)return actor;const [created]=await db().begin(async tx=>{const rows=await tx`INSERT INTO surveys (business_head_id,title,description,survey_type,anonymous,questions,opens_at,closes_at,created_by) VALUES (${input.businessHeadId||null},${input.title},${input.description||null},${input.surveyType},${input.anonymous},${JSON.stringify(input.questions)}::jsonb,${input.opensAt},${input.closesAt},${actor.id}) RETURNING *`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${actor.id},'survey.create','survey',${rows[0].id},${input.businessHeadId||null},${JSON.stringify({title:input.title,type:input.surveyType,anonymous:input.anonymous,questionCount:input.questions.length,opensAt:input.opensAt,closesAt:input.closesAt})}::jsonb,'Survey draft created')`;return rows;});return ok(created,{status:201});}catch(error){return apiError(error);}}
