import { z } from "zod";
import { apiError, fail, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";

const schema=z.object({employeeId:z.uuid(),separationType:z.enum(['resignation','termination','retirement','contract_completion','abandonment']),submittedDate:z.iso.date(),proposedLastWorkingDate:z.iso.date(),reason:z.string().min(5).max(2000),noticeDays:z.number().int().min(0).max(365).default(0)}).refine(v=>v.proposedLastWorkingDate>=v.submittedDate,{message:'Last working date must not precede submission'});

export async function GET(request:Request){try{const head=new URL(request.url).searchParams.get('businessHeadId');const user=await requireApiUser('separation:read',head);if(user instanceof Response)return user;return ok(await db()`SELECT s.*,e.employee_code,concat_ws(' ',e.first_name,e.last_name) AS employee_name,e.position,e.business_head_id,b.name AS business_head,(SELECT count(*)::int FROM separation_tasks t WHERE t.separation_id=s.id) AS task_count,(SELECT count(*)::int FROM separation_tasks t WHERE t.separation_id=s.id AND t.status='completed') AS completed_tasks FROM separations s JOIN employees e ON e.id=s.employee_id JOIN business_heads b ON b.id=e.business_head_id WHERE (${head}::uuid IS NULL OR e.business_head_id=${head}::uuid) ORDER BY s.proposed_last_working_date`);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const sql=db();const [employee]=await sql<{business_head_id:string;status:string}[]>`SELECT business_head_id,status FROM employees WHERE id=${input.employeeId}`;if(!employee)return fail('Employee not found',404);const user=await requireApiUser('separation:write',employee.business_head_id);if(user instanceof Response)return user;const [row]=await sql.begin(async tx=>{const rows=await tx`INSERT INTO separations (employee_id,separation_type,submitted_date,proposed_last_working_date,reason,notice_days,created_by) VALUES (${input.employeeId},${input.separationType},${input.submittedDate},${input.proposedLastWorkingDate},${input.reason},${input.noticeDays},${user.id}) RETURNING *`;const tasks=[['Manager','Complete knowledge transfer'],['IT','Revoke accounts and collect devices'],['Administration','Collect assets and complete no-dues'],['Finance','Calculate full and final settlement'],['HR','Conduct exit interview and issue letters']];for(const [category,title] of tasks)await tx`INSERT INTO separation_tasks (separation_id,category,title,due_date) VALUES (${rows[0].id},${category},${title},${input.proposedLastWorkingDate})`;await tx`UPDATE employees SET status='notice_period',notice_start_date=${input.submittedDate},last_working_date=${input.proposedLastWorkingDate},updated_at=now() WHERE id=${input.employeeId}`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'separation.start','separation',${rows[0].id},${employee.business_head_id},${JSON.stringify(rows[0])}::jsonb,${input.reason})`;return rows;});return ok(row,{status:201});}catch(e){return apiError(e);}}
