"use client";
/* Administration payloads vary by permission and record type. */
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */

import { FormEvent, useCallback, useEffect, useState } from "react";

type Head = { id: string; name: string };
type Tab = "organisation" | "access" | "policies" | "workflows" | "compliance" | "audit";
type FormKind = "master" | "user" | "role" | "policy" | "workflow" | "compliance";

const friendly = (value: unknown) => String(value || "—").replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const dateOnly = (value: unknown) => value ? String(value).slice(0, 10) : "—";
const statusClass = (value: unknown) => String(value || "active").toLowerCase().replaceAll("_", "-");

async function parse(response: Response) {
  const body = await response.json().catch(() => null);
  if (!response.ok) throw new Error(body?.error?.message || "The administration action could not be completed.");
  return body?.data;
}
async function optional(path: string) { const response = await fetch(path); if ([401, 403, 404].includes(response.status)) return null; return parse(response); }

export function AdministrationWorkspace({ businessHeadId, head, heads, flash }: { businessHeadId: string; head: string; heads: Head[]; flash: (message: string) => void }) {
  const [tab, setTab] = useState<Tab>("organisation"); const [busy, setBusy] = useState(true); const [refresh, setRefresh] = useState(0); const [form, setForm] = useState<FormKind | null>(null); const [targetUser, setTargetUser] = useState<any>(null);
  const [masters, setMasters] = useState<any>(null); const [users, setUsers] = useState<any[] | null>(null); const [changes, setChanges] = useState<any[] | null>(null); const [policies, setPolicies] = useState<any[] | null>(null); const [workflows, setWorkflows] = useState<any[] | null>(null); const [audit, setAudit] = useState<any[] | null>(null);const[compliance,setCompliance]=useState<any[]|null>(null);
  const scoped = useCallback((path: string) => businessHeadId === "all" ? path : `${path}${path.includes("?") ? "&" : "?"}businessHeadId=${encodeURIComponent(businessHeadId)}`, [businessHeadId]);
  const load = useCallback(async () => { setBusy(true); try { const [masterRows, userRows, changeRows, policyRows, workflowRows, auditRows,complianceRows] = await Promise.all([optional(scoped("/api/organisation/masters")), optional("/api/admin/users"), optional("/api/admin/permission-changes?status=pending"), optional(scoped("/api/policies")), optional("/api/workflows/definitions"), optional(scoped("/api/audit")),optional(scoped("/api/compliance"))]); setMasters(masterRows); setUsers(userRows); setChanges(changeRows); setPolicies(policyRows); setWorkflows(workflowRows); setAudit(auditRows);setCompliance(complianceRows); } catch (error) { flash((error as Error).message); } finally { setBusy(false); } }, [scoped, flash]);
  useEffect(() => { load(); }, [load, refresh]);
  async function post(path: string, payload: unknown, method = "POST") { await parse(await fetch(path, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(payload) })); setRefresh(value => value + 1); }
  async function toggleUser(user: any) { const active = !user.active; const reason = window.prompt(`Reason to ${active ? "activate" : "deactivate"} ${user.full_name}:`, active ? "Access restored by administrator" : "Access removed by administrator"); if (!reason) return; try { await post(`/api/admin/users/${user.id}`, { active, reason }, "PATCH"); flash(`User ${active ? "activated" : "deactivated"}.`); } catch (error) { flash((error as Error).message); } }
  async function decideChange(change: any) { const decision = window.confirm(`Approve the role change for ${change.target_name}?`) ? "approve" : "reject"; const reason = window.prompt(`Reason to ${decision}:`, decision === "approve" ? "Scope and least-privilege access independently verified" : "Permission request requires correction"); if (!reason) return; try { await post(`/api/admin/permission-changes/${change.id}/decision`, { decision, reason }); flash(`Permission change ${decision}d.`); } catch (error) { flash((error as Error).message); } }
  async function decidePolicy(policy: any) { if (!["draft", "pending"].includes(policy.status)) return flash(`Policy is ${friendly(policy.status).toLowerCase()}.`); const decision = window.confirm(`Approve ${policy.title} v${policy.version}?`) ? "approve" : "reject"; const reason = window.prompt(`Reason to ${decision}:`, decision === "approve" ? "Policy content and effective date independently reviewed" : "Policy version needs correction"); if (!reason) return; try { await post(`/api/policies/${policy.id}/decision`, { decision, reason }); flash(`Policy ${decision}d.`); } catch (error) { flash((error as Error).message); } }
  async function decideWorkflow(version: any) { if (!["draft", "pending"].includes(version.status)) return flash(`Workflow version is ${friendly(version.status).toLowerCase()}.`); const decision = window.confirm(`Approve workflow v${version.version}?`) ? "approve" : "reject"; const reason = window.prompt(`Reason to ${decision}:`, decision === "approve" ? "Trigger, approver roles, SLA and actions independently verified" : "Workflow version needs correction"); if (!reason) return; try { await post(`/api/workflows/definitions/${version.id}/decision`, { decision, reason }); flash(`Workflow version ${decision}d.`); } catch (error) { flash((error as Error).message); } }
  async function advanceCompliance(item:any){const action=["pending","overdue"].includes(item.status)?"start":item.status==="in_progress"?"file":item.status==="filed"?"complete":"reopen";const reason=window.prompt(`Reason to ${action}:`,`Compliance obligation ${action}`);if(!reason)return;const referenceNumber=action==="file"?window.prompt("Filing/reference number:")||null:null;try{await post(`/api/compliance/${item.id}/transition`,{action,reason,referenceNumber,evidenceDocumentId:null});flash(`Compliance item moved to ${friendly(action).toLowerCase()}.`)}catch(error){flash((error as Error).message)}}
  const masterCount = masters ? ["legalEntities", "locations", "costCentres", "positions", "departments"].reduce((sum, key) => sum + Number(masters[key]?.length || 0), 0) : 0;
  return <>
    <div className="page-head"><div><span className="eyebrow">Settings</span><h1>Settings</h1><p>{head} · Companies, departments, logins, policies, approvals and a record of every change.</p></div>{tab === "organisation" ? <button className="primary" onClick={() => setForm("master")}>＋ Add department, location or job</button> : tab === "access" && users ? <button className="primary" onClick={() => setForm("user")}>＋ Give someone a login</button> : tab === "policies" ? <button className="primary" onClick={() => setForm("policy")}>＋ New policy version</button> : tab === "workflows" ? <button className="primary" onClick={() => setForm("workflow")}>＋ New workflow version</button> :tab==="compliance"?<button className="primary" onClick={()=>setForm("compliance")}>＋ Add compliance item</button>: null}</div>
    <div className="metrics compact"><AdminMetric label="DEPARTMENTS & JOBS" value={masterCount} icon="▦" tone="purple" /><AdminMetric label="PEOPLE WHO CAN LOG IN" value={users?.filter(user => user.active).length || 0} icon="◎" tone="green" /><AdminMetric label="ACCESS REQUESTS" value={changes?.length || 0} icon="!" tone="orange" /><AdminMetric label="CHANGES RECORDED" value={audit?.length || 0} icon="✓" tone="blue" /></div>
    <section className="panel admin-tabs"><nav>{(["organisation", "access", "policies", "workflows", "compliance", "audit"] as Tab[]).map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{({organisation:"Company setup",access:"Logins & roles",policies:"Policies",workflows:"Approval steps",compliance:"Compliance",audit:"Change history"} as Record<string,string>)[item]||friendly(item)}</button>)}</nav><span>Every change is recorded with who made it</span></section>
    {busy ? <section className="panel loading-panel">Loading…</section> : <>
      {tab === "organisation" && (masters ? <div className="admin-master-grid"><MasterList title="Companies (legal entities)" rows={masters.legalEntities} primary="legal_name" secondary="country_code" /><MasterList title="Work locations" rows={masters.locations} primary="name" secondary="code" /><MasterList title="Departments" rows={masters.departments} primary="name" secondary="business_head_name" /><MasterList title="Cost centres" rows={masters.costCentres} primary="name" secondary="department" /><MasterList title="Job titles" rows={masters.positions} primary="title" secondary="department" /></div> : <Unavailable text="Organisation configuration is outside your current permission scope." />)}
      {tab === "access" && <div className="grid halves"><section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>People who can log in</h2><p>{users ? `${users.length} user account(s)` : "Restricted to system administrators"}</p></div></div>{users?.map((user, index) => <button key={user.id} onClick={() => { setTargetUser(user); setForm("role"); }}><i>{index + 1}</i><div><b>{user.full_name}</b><span>{user.email} · {user.roles?.map((role: any) => role.code).join(", ") || "No roles"}</span></div><em className={`status ${user.active ? "active" : "cancelled"}`}>{user.active ? "Active" : "Inactive"}</em><strong>›</strong></button>)}{!users && <Unavailable text="User administration requires admin permission." />}{users?.map(user => <button className="admin-user-toggle" key={`toggle-${user.id}`} onClick={() => toggleUser(user)}>{user.active ? "Deactivate" : "Activate"} {user.full_name}</button>)}</section><section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Permission approvals</h2><p>Four-eyes review for role and scope changes</p></div></div>{changes?.map((change, index) => <button key={change.id} onClick={() => decideChange(change)}><i>{index + 1}</i><div><b>{change.target_name}</b><span>Requested by {change.requested_by_name} · {change.request_reason}</span></div><em className="status pending">Pending</em><strong>›</strong></button>)}{changes && !changes.length && <Unavailable text="No permission changes await review." />}{!changes && <Unavailable text="Only a global super administrator can review permission changes." />}</section></div>}
      {tab === "policies" && (policies ? <section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Policy library</h2><p>Effective-dated content and employee acknowledgement counts</p></div></div>{policies.map((policy, index) => <button key={policy.id} onClick={() => decidePolicy(policy)}><i>{index + 1}</i><div><b>{policy.code} v{policy.version} · {policy.title}</b><span>{policy.business_head || "All Velite"} · effective {dateOnly(policy.effective_from)} · {policy.acknowledged_count} acknowledgement(s)</span></div><em className={`status ${statusClass(policy.status)}`}>{friendly(policy.status)}</em><strong>›</strong></button>)}</section> : <Unavailable text="Policy administration is outside your current permission scope." />)}
      {tab === "workflows" && (workflows ? <section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Approval steps</h2><p>Who approves what, and how quickly</p></div></div>{workflows.map((workflow, index) => { const version = workflow.versions?.[0]; return <button key={workflow.id} onClick={() => version && decideWorkflow(version)}><i>{index + 1}</i><div><b>{workflow.code} · {workflow.name}</b><span>{friendly(workflow.record_type)} · {version?.steps?.length || 0} step(s) · v{version?.version || "—"}</span></div><em className={`status ${statusClass(version?.status)}`}>{friendly(version?.status || "No version")}</em><strong>›</strong></button>; })}</section> : <Unavailable text="Workflow administration is outside your current permission scope." />)}
      {tab === "compliance" && (compliance?<section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Compliance due dates</h2><p>PF, ESI and other filings — who owns each and when it is due</p></div></div>{compliance.map((item,index)=><button key={item.id} onClick={()=>advanceCompliance(item)}><i>{index+1}</i><div><b>{item.compliance_type} · {item.period}</b><span>{item.business_head} · due {dateOnly(item.due_date)} · owner {item.owner||"Unassigned"}{item.reference_number?` · ref ${item.reference_number}`:""}</span></div><em className={`status ${item.overdue?"rejected":statusClass(item.status)}`}>{item.overdue?"Overdue":friendly(item.status)}</em><strong>›</strong></button>)}{!compliance.length&&<Unavailable text="No compliance obligations have been configured."/>}</section>:<Unavailable text="Compliance records require reporting permission."/>)}
      {tab === "audit" && (audit ? <section className="panel table-panel audit-table"><div className="data-table"><div className="tr th"><span>TIME</span><span>ACTOR</span><span>ACTION</span><span>RECORD</span><span>REASON</span></div>{audit.map(event => <div className="tr" key={event.id}><span>{new Date(event.occurred_at).toLocaleString("en-IN")}</span><span><b>{event.actor || "System"}<small>{event.actor_email || "Background service"}</small></b></span><span>{friendly(event.action)}</span><span>{friendly(event.entity_type)}<small>{event.entity_id || "—"}</small></span><span>{event.reason || "—"}</span></div>)}</div></section> : <Unavailable text="Audit evidence requires reporting permission." />)}
    </>}
    {form && <AdminForm kind={form} heads={heads} selectedHead={businessHeadId} targetUser={targetUser} onClose={() => { setForm(null); setTargetUser(null); }} onSaved={() => { setForm(null); setTargetUser(null); setRefresh(value => value + 1); flash("Administration record saved with an audit entry."); }} />}
  </>;
}

function AdminMetric({ label, value, icon, tone }: { label: string; value: number; icon: string; tone: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><span>{label}</span><strong>{value}</strong></div>; }
function Unavailable({ text }: { text: string }) { return <section className="panel admin-unavailable">{text}</section>; }
function MasterList({ title, rows, primary, secondary }: { title: string; rows: any[]; primary: string; secondary: string }) { return <section className="panel"><div className="panel-head padded"><div><h2>{title}</h2><p>{rows?.length || 0} configured</p></div></div><div className="master-list">{(rows || []).map(row => <div key={row.id}><span>{String(row[primary] || row.code || "M").slice(0, 1)}</span><div><strong>{row[primary] || row.name || row.code}</strong><small>{row[secondary] || row.code || "Active"}</small></div></div>)}{!rows?.length && <div className="empty-state padded">No records configured.</div>}</div></section>; }

const roles = ["SUPER_ADMIN", "HR_ADMIN", "HR_OPERATIONS", "RECRUITER", "MANAGER", "DEPARTMENT_HEAD", "PAYROLL_ADMIN", "FINANCE_APPROVER", "LEADERSHIP", "AUDITOR", "EMPLOYEE", "IT_FACILITIES"];
function AdminForm({ kind, heads, selectedHead, targetUser, onClose, onSaved }: { kind: FormKind; heads: Head[]; selectedHead: string; targetUser: any; onClose: () => void; onSaved: () => void }) {
  const [headId, setHeadId] = useState(selectedHead === "all" ? heads[0]?.id || "" : selectedHead); const [departments, setDepartments] = useState<any[]>([]); const [masterKind, setMasterKind] = useState("legal_entity"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const today = new Date().toISOString().slice(0, 10);
  useEffect(() => { if (headId) fetch(`/api/departments?businessHeadId=${encodeURIComponent(headId)}`).then(response => response.ok ? response.json() : ({ data: [] })).then(body => setDepartments(body.data || [])); }, [headId]);
  const titles: Record<FormKind, string> = { master: "Add department, location or job", user: "Give someone a login", role: "Change what this person can do", policy: "Add or update a policy", workflow: "Set up approval steps",compliance:"Add a compliance due date" };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const values = new FormData(event.currentTarget); let path = ""; let method = "POST"; let payload: any = {};
    if (kind === "master") { path = "/api/organisation/masters"; const code = String(values.get("code") || "").toUpperCase(); if (masterKind === "legal_entity") payload = { kind: masterKind, businessHeadId: headId, name: values.get("name"), legalName: values.get("legalName"), countryCode: "IN", taxIdentifier: values.get("taxIdentifier") || null }; if (masterKind === "work_location") payload = { kind: masterKind, businessHeadId: headId, code, name: values.get("name"), timezone: "Asia/Kolkata", address: { city: String(values.get("city") || ""), state: String(values.get("state") || ""), country: "India" } }; if (masterKind === "department") payload = { kind: masterKind, businessHeadId: headId, code, name: values.get("name") }; if (masterKind === "cost_centre") payload = { kind: masterKind, businessHeadId: headId, code, name: values.get("name"), departmentId: values.get("departmentId") || null }; if (masterKind === "job_position") payload = { kind: masterKind, businessHeadId: headId, code, title: values.get("name"), departmentId: values.get("departmentId") || null, grade: values.get("grade") || null }; }
    if (kind === "user") { path = "/api/admin/users"; const role = String(values.get("role")); const global = values.get("global") === "on" || role === "SUPER_ADMIN"; payload = { email: values.get("email"), fullName: values.get("fullName"), temporaryPassword: values.get("temporaryPassword"), roles: [{ code: role, businessHeadId: global ? null : headId, departmentId: global ? null : values.get("departmentId") || null }] }; }
    if (kind === "role") { path = `/api/admin/users/${targetUser.id}/roles`; method = "PUT"; const role = String(values.get("role")); const global = values.get("global") === "on" || role === "SUPER_ADMIN"; payload = { roles: [{ code: role, businessHeadId: global ? null : headId, departmentId: global ? null : values.get("departmentId") || null }], reason: values.get("reason") }; }
    if (kind === "policy") { path = "/api/policies"; payload = { businessHeadId: values.get("global") === "on" ? null : headId, code: String(values.get("code") || "").toUpperCase(), title: values.get("title"), content: values.get("content"), effectiveFrom: values.get("effectiveFrom"), mandatory: values.get("mandatory") === "on", changeReason: values.get("reason") }; }
    if (kind === "workflow") { path = "/api/workflows/definitions"; const stepCode = String(values.get("stepCode") || "review").toLowerCase().replace(/[^a-z0-9_]/g, "_"); payload = { code: String(values.get("code") || "").toUpperCase(), name: values.get("name"), recordType: String(values.get("recordType") || "hr_record").toLowerCase().replace(/[^a-z0-9_]/g, "_"), scope: values.get("global") === "on" ? {} : { businessHeadId: headId }, triggerConfig: { event: values.get("triggerEvent") }, steps: [{ code: stepCode, title: values.get("stepTitle"), approverRoles: [values.get("approverRole")], slaHours: Number(values.get("slaHours")), actions: ["approve", "reject", "return"] }], effectiveFrom: values.get("effectiveFrom"), effectiveTo: null, changeReason: values.get("reason") }; }
    if(kind==="compliance"){path="/api/compliance";payload={businessHeadId:headId,complianceType:values.get("complianceType"),period:values.get("period"),dueDate:values.get("dueDate"),amount:values.get("amount")?Number(values.get("amount")):null,notes:values.get("notes")||null};}
    try { await parse(await fetch(path, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(payload) })); onSaved(); } catch (submissionError) { setError((submissionError as Error).message); setBusy(false); }
  }
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="eyebrow">Settings</span><h2>{titles[kind]}</h2></div><button onClick={onClose}>×</button></div><form className="form-grid" onSubmit={submit}>
    {kind === "master" && <><label>Master type<select value={masterKind} onChange={event => setMasterKind(event.target.value)}><option value="legal_entity">Legal entity</option><option value="work_location">Work location</option><option value="department">Department</option><option value="cost_centre">Cost centre</option><option value="job_position">Job position</option></select></label><HeadField heads={heads} value={headId} onChange={setHeadId} />{masterKind !== "legal_entity" && <label>Code<input name="code" required /></label>}<label>{masterKind === "job_position" ? "Position title" : "Name"}<input name="name" required /></label>{masterKind === "legal_entity" && <><label>Legal name<input name="legalName" required /></label><label>Tax identifier<input name="taxIdentifier" /></label></>}{masterKind === "work_location" && <><label>City<input name="city" required /></label><label>State<input name="state" required /></label></>}{["cost_centre", "job_position"].includes(masterKind) && <label>Department<select name="departmentId"><option value="">Not assigned</option>{departments.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>}{masterKind === "job_position" && <label>Grade<input name="grade" /></label>}</>}
    {(kind === "user" || kind === "role") && <><HeadField heads={heads} value={headId} onChange={setHeadId} />{kind === "user" && <><label>Full name<input name="fullName" required /></label><label>Email<input name="email" type="email" required /></label><label className="span-two">Temporary password<input name="temporaryPassword" type="password" minLength={12} required /></label></>}<label>Role<select name="role" defaultValue={kind === "role" ? targetUser?.roles?.[0]?.code || "EMPLOYEE" : "EMPLOYEE"}>{roles.map(role => <option key={role} value={role}>{friendly(role)}</option>)}</select></label><label>Department<select name="departmentId"><option value="">All departments in the head</option>{departments.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="check-label span-two"><input name="global" type="checkbox" /> Global, unscoped role</label>{kind === "role" && <label className="span-two">Reason<input name="reason" required /></label>}<div className="form-hint span-two">Role changes are submitted for approval by a different global super administrator.</div></>}
    {kind === "policy" && <><HeadField heads={heads} value={headId} onChange={setHeadId} /><label>Policy code<input name="code" pattern="[A-Za-z][A-Za-z0-9_-]+" required /></label><label className="span-two">Title<input name="title" required /></label><label>Effective from<input name="effectiveFrom" type="date" defaultValue={today} required /></label><label className="check-label"><input name="mandatory" type="checkbox" defaultChecked /> Mandatory acknowledgement</label><label className="check-label span-two"><input name="global" type="checkbox" /> Apply to all Velite business heads</label><label className="span-two">Policy content<textarea name="content" rows={7} required /></label><label className="span-two">Change reason<input name="reason" required /></label></>}
    {kind === "workflow" && <><HeadField heads={heads} value={headId} onChange={setHeadId} /><label>Workflow code<input name="code" pattern="[A-Za-z][A-Za-z0-9_]+" required /></label><label>Workflow name<input name="name" required /></label><label>Record type<input name="recordType" placeholder="attendance_correction" required /></label><label>Trigger event<input name="triggerEvent" placeholder="record.submitted" required /></label><label>Step code<input name="stepCode" defaultValue="manager_review" required /></label><label>Step title<input name="stepTitle" defaultValue="Manager review" required /></label><label>Approver role<select name="approverRole" defaultValue="MANAGER">{roles.filter(role => role !== "EMPLOYEE").map(role => <option key={role}>{role}</option>)}</select></label><label>SLA hours<input name="slaHours" type="number" min="1" max="8760" defaultValue="48" required /></label><label>Effective from<input name="effectiveFrom" type="date" defaultValue={today} required /></label><label className="check-label"><input name="global" type="checkbox" /> Global workflow</label><label className="span-two">Change reason<input name="reason" required /></label></>}
    {kind==="compliance"&&<><HeadField heads={heads} value={headId} onChange={setHeadId}/><label>Compliance type<input name="complianceType" placeholder="Provident Fund filing" required/></label><label>Period<input name="period" placeholder="2026-07" required/></label><label>Due date<input name="dueDate" type="date" defaultValue={today} required/></label><label>Amount, if applicable<input name="amount" type="number" min="0" step="0.01"/></label><label className="span-two">Notes<textarea name="notes" rows={4}/></label></>}
    {error && <div className="form-error span-two">{error}</div>}<div className="modal-actions span-two"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Saving…" : "Save and continue"}</button></div>
  </form></section></div>;
}
function HeadField({ heads, value, onChange }: { heads: Head[]; value: string; onChange: (value: string) => void }) { return <label>Business head<select value={value} onChange={event => onChange(event.target.value)} required>{heads.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>; }
