"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { FormEvent, useCallback, useEffect, useState } from "react";

type Head={id:string;name:string}; type Tab="surveys"|"recognition"; type FormKind=Tab|null;
const friendly=(value:unknown)=>String(value||"—").replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
async function parse(response:Response){const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message||"The engagement action could not be completed.");return body?.data;}

export function EngagementWorkspace({businessHeadId,head,heads,people,flash}:{businessHeadId:string;head:string;heads:Head[];people:any[];flash:(message:string)=>void}){
  const[tab,setTab]=useState<Tab>("surveys");const[surveys,setSurveys]=useState<any[]>([]);const[recognitions,setRecognitions]=useState<any[]>([]);const[busy,setBusy]=useState(true);const[refresh,setRefresh]=useState(0);const[form,setForm]=useState<FormKind>(null);
  const scoped=useCallback((path:string)=>businessHeadId==="all"?path:`${path}?businessHeadId=${encodeURIComponent(businessHeadId)}`,[businessHeadId]);
  useEffect(()=>{setBusy(true);Promise.all([fetch(scoped("/api/engagement/surveys")).then(parse),fetch(scoped("/api/engagement/recognitions")).then(parse)]).then(([surveyRows,recognitionRows])=>{setSurveys(surveyRows||[]);setRecognitions(recognitionRows||[])}).catch(error=>flash(error.message)).finally(()=>setBusy(false))},[scoped,refresh,flash]);
  async function advance(survey:any){const action=["draft","rejected"].includes(survey.status)?"submit":survey.status==="pending"?(window.confirm("Approve this survey?")?"approve":"reject"):survey.status==="approved"?"close":null;if(!action)return;const reason=window.prompt(`Reason to ${action}:`,action==="approve"?"Questions, anonymity and audience independently reviewed":"Survey workflow progressed");if(!reason)return;try{await parse(await fetch(`/api/engagement/surveys/${survey.id}/transition`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,reason})}));setRefresh(value=>value+1);flash(`Survey ${friendly(action).toLowerCase()}d.`)}catch(error){flash((error as Error).message)}}
  return <><div className="page-head"><div><span className="eyebrow">Surveys & recognition</span><h1>Surveys & recognition</h1><p>{head} · Ask staff for their views, and thank people for good work.</p></div><button className="primary" onClick={()=>setForm(tab)}>＋ {tab==="surveys"?"Create survey":"Recognise colleague"}</button></div>
    <div className="metrics compact"><Metric label="SURVEYS" value={surveys.length} icon="◉" tone="purple"/><Metric label="OPEN RESPONSES" value={surveys.filter(item=>item.status==="approved").reduce((sum,item)=>sum+Number(item.response_count||0),0)} icon="✓" tone="green"/><Metric label="RECOGNITIONS" value={recognitions.length} icon="☆" tone="orange"/><Metric label="ANONYMOUS" value={surveys.filter(item=>item.anonymous).length} icon="◇" tone="blue"/></div>
    <section className="panel admin-tabs"><nav>{(["surveys","recognition"] as Tab[]).map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{friendly(item)}</button>)}</nav><span>Survey makers cannot approve their own survey</span></section>
    {busy?<section className="panel loading-panel">Loading engagement records…</section>:tab==="surveys"?<section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Employee listening</h2><p>Pulse, onboarding, engagement and exit surveys</p></div></div>{surveys.map((item,index)=><button key={item.id} onClick={()=>advance(item)}><i>{index+1}</i><div><b>{item.title}</b><span>{friendly(item.survey_type)} · {item.anonymous?"Anonymous":"Identified"} · closes {String(item.closes_at).slice(0,10)} · {item.response_count} response(s)</span></div><em className={`status ${item.status}`}>{friendly(item.status)}</em><strong>›</strong></button>)}{!surveys.length&&<div className="empty-state padded">No surveys have been created.</div>}</section>:<section className="panel recognition-grid">{recognitions.map(item=><article key={item.id}><div className="avatar lilac">☆</div><div><strong>{item.recipient_name}</strong><span>{friendly(item.recognition_type)} · from {item.sender_name||"Velite"}</span><p>{item.message}</p><small>{new Date(item.created_at).toLocaleDateString("en-IN")}</small></div></article>)}{!recognitions.length&&<div className="empty-state padded">No recognition has been published.</div>}</section>}
    {form&&<EngagementForm kind={form} heads={heads} people={people} selectedHead={businessHeadId} onClose={()=>setForm(null)} onSaved={()=>{setForm(null);setRefresh(value=>value+1);flash("Engagement record saved with an audit entry.")}}/>}
  </>;
}
function Metric({label,value,icon,tone}:{label:string;value:number;icon:string;tone:string}){return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><span>{label}</span><strong>{value}</strong><small>Current authorised scope</small></div>}
function EngagementForm({kind,heads,people,selectedHead,onClose,onSaved}:{kind:Tab;heads:Head[];people:any[];selectedHead:string;onClose:()=>void;onSaved:()=>void}){const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[headId,setHeadId]=useState(selectedHead==="all"?heads[0]?.id||"":selectedHead);const now=new Date(),later=new Date(Date.now()+14*86400000);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const values=new FormData(event.currentTarget);const payload=kind==="surveys"?{businessHeadId:values.get("global")==="on"?null:headId,title:values.get("title"),description:values.get("description")||null,surveyType:values.get("surveyType"),anonymous:values.get("anonymous")==="on",questions:[{code:"score",prompt:values.get("question"),type:"rating",required:true}],opensAt:new Date(String(values.get("opensAt"))).toISOString(),closesAt:new Date(String(values.get("closesAt"))).toISOString()}:{recipientEmployeeId:values.get("recipientEmployeeId"),recognitionType:values.get("recognitionType"),message:values.get("message"),public:values.get("public")==="on"};try{await parse(await fetch(kind==="surveys"?"/api/engagement/surveys":"/api/engagement/recognitions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}));onSaved()}catch(submissionError){setError((submissionError as Error).message);setBusy(false)}}
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="eyebrow">ENGAGEMENT</span><h2>{kind==="surveys"?"Create listening survey":"Recognise a colleague"}</h2></div><button onClick={onClose}>×</button></div><form className="form-grid" onSubmit={submit}>{kind==="surveys"?<><label>Business head<select value={headId} onChange={event=>setHeadId(event.target.value)}>{heads.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Survey type<select name="surveyType"><option value="pulse">Pulse</option><option value="engagement">Engagement</option><option value="onboarding">Onboarding</option><option value="exit">Exit</option></select></label><label className="span-two">Title<input name="title" required/></label><label className="span-two">Description<input name="description"/></label><label className="span-two">Rating question<input name="question" defaultValue="How likely are you to recommend Velite as a place to work?" required/></label><label>Opens at<input name="opensAt" type="datetime-local" defaultValue={now.toISOString().slice(0,16)} required/></label><label>Closes at<input name="closesAt" type="datetime-local" defaultValue={later.toISOString().slice(0,16)} required/></label><label className="check-label"><input name="anonymous" type="checkbox" defaultChecked/> Anonymous responses</label><label className="check-label"><input name="global" type="checkbox"/> All Velite heads</label><div className="form-hint span-two">The survey starts as a draft and needs approval by a different authorised user.</div></>:<><label className="span-two">Employee<select name="recipientEmployeeId" required>{people.map(person=><option key={person.id} value={person.id}>{person.name} · {person.head}</option>)}</select></label><label>Recognition type<select name="recognitionType"><option>Above and Beyond</option><option>Customer Excellence</option><option>Innovation</option><option>Teamwork</option><option>Values Champion</option></select></label><label className="check-label"><input name="public" type="checkbox" defaultChecked/> Show publicly</label><label className="span-two">Recognition message<textarea name="message" rows={5} required/></label></>}{error&&<div className="form-error span-two">{error}</div>}<div className="modal-actions span-two"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save and continue"}</button></div></form></section></div>}
