"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type CalendarEvent = { id: string; event_date: string; event_type: string; title: string; employee_name: string | null; business_head: string | null; status: string; source_record_type: string | null };
const ymd = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const friendly = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());

async function bodyData(response: Response) { const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error?.message || "Calendar action failed."); return body?.data; }

export function HrCalendarWorkspace({ businessHeadId, head, flash }: { businessHeadId: string; head: string; flash: (message: string) => void }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [events, setEvents] = useState<CalendarEvent[]>([]); const [busy, setBusy] = useState(true); const [creating, setCreating] = useState(false); const [refresh, setRefresh] = useState(0); const [type, setType] = useState("all");
  const range = useMemo(() => { const from = new Date(month.getFullYear(), month.getMonth(), 1); const to = new Date(month.getFullYear(), month.getMonth() + 2, 0); return { from: ymd(from), to: ymd(to) }; }, [month]);
  const load = useCallback(() => { const params = new URLSearchParams(range); if (businessHeadId !== "all") params.set("businessHeadId", businessHeadId); fetch(`/api/calendar?${params}`).then(bodyData).then(rows => setEvents(rows || [])).catch(error => flash(error.message)).finally(() => setBusy(false)); }, [range, businessHeadId, flash]);
  useEffect(() => load(), [load, refresh]);
  const first = (new Date(month.getFullYear(), month.getMonth(), 1).getDay() + 6) % 7; const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const days = Array.from({ length: 42 }, (_, index) => index >= first && index < first + count ? index - first + 1 : null);
  const filtered = type === "all" ? events : events.filter(event => event.event_type === type); const types = [...new Set(events.map(event => event.event_type))].sort(); const today = ymd(new Date());
  const byDay = useMemo(() => new Map(Array.from({ length: count }, (_, index) => { const date = ymd(new Date(month.getFullYear(), month.getMonth(), index + 1)); return [index + 1, filtered.filter(event => String(event.event_date).slice(0, 10) === date)]; })), [count, month, filtered]);
  async function sync() { try { const result = await bodyData(await fetch("/api/calendar/generate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ businessHeadId: businessHeadId === "all" ? null : businessHeadId }) })); const total = Object.values(result || {}).reduce((sum: number, item: any) => sum + Number(item.inserted || 0) + Number(item.updated || 0), 0); setRefresh(value => value + 1); flash(`${total} calendar milestone(s) synchronised.`); } catch (error) { flash((error as Error).message); } }
  return <>
    <div className="page-head"><div><span className="eyebrow">Calendar</span><h1>Calendar</h1><p>{head} · Joining days, probation ends, salary dates, appraisals, training and other important dates.</p></div><button className="primary" onClick={() => setCreating(true)}>＋ Add a date</button></div>
    <div className="metrics compact"><CalendarMetric label="THIS VIEW" value={filtered.length} icon="□" tone="purple" /><CalendarMetric label="THIS MONTH" value={filtered.filter(event => String(event.event_date).slice(0, 7) === ymd(month).slice(0, 7)).length} icon="◎" tone="blue" /><CalendarMetric label="EMPLOYEE EVENTS" value={filtered.filter(event => event.employee_name).length} icon="✓" tone="green" /><CalendarMetric label="SYSTEM MILESTONES" value={filtered.filter(event => event.source_record_type).length} icon="◷" tone="orange" /></div>
    <section className="panel operations-toolbar"><div><strong>Calendar controls</strong><span>Source dates are synchronised, so rescheduling does not leave stale duplicates</span></div><div><select value={type} onChange={event => setType(event.target.value)} aria-label="Calendar event type"><option value="all">All event types</option>{types.map(item => <option key={item} value={item}>{friendly(item)}</option>)}</select><button className="secondary" onClick={sync}>Synchronise milestones</button><button className="secondary" onClick={() => { setMonth(new Date(new Date().getFullYear(), new Date().getMonth(), 1)); }}>Today</button></div></section>
    <div className="calendar-layout calendar-workspace"><section className="panel mini-calendar"><div className="month-head"><button aria-label="Previous month" onClick={() => setMonth(current => new Date(current.getFullYear(), current.getMonth() - 1, 1))}>‹</button><h2>{month.toLocaleString("en-IN", { month: "long", year: "numeric" })}</h2><button aria-label="Next month" onClick={() => setMonth(current => new Date(current.getFullYear(), current.getMonth() + 1, 1))}>›</button></div><div className="weekdays">{["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"].map(day => <span key={day}>{day}</span>)}</div><div className="days">{days.map((day, index) => { const date = day ? ymd(new Date(month.getFullYear(), month.getMonth(), day)) : ""; const eventCount = day ? byDay.get(day)?.length || 0 : 0; return <button key={index} disabled={!day} className={`${date === today ? "today" : ""} ${eventCount ? "event" : ""}`.trim()} title={eventCount ? `${eventCount} milestone(s)` : undefined}>{day || ""}{eventCount > 1 && <small>{eventCount}</small>}</button>; })}</div></section>
      <section className="panel agenda"><div className="panel-head padded"><div><h2>Milestone agenda</h2><p>{range.from} to {range.to}</p></div></div>{busy ? <div className="empty-state padded">Loading calendar…</div> : filtered.map((event, index) => { const date = new Date(`${String(event.event_date).slice(0, 10)}T00:00:00`); return <div className="calendar-item" key={event.id}><div className={`datebox ${["violet", "blue", "green", "orange"][index % 4]}`}><strong>{String(date.getDate()).padStart(2, "0")}</strong><span>{date.toLocaleString("en-IN", { month: "short" }).toUpperCase()}</span></div><div><strong>{event.title}</strong><span>{event.employee_name || event.business_head || "All Velite"}</span></div><b>{friendly(event.event_type)}</b></div>; })}{!busy && !filtered.length && <div className="empty-state padded">No milestones match this period and filter.</div>}</section></div>
    {creating && <CalendarForm businessHeadId={businessHeadId} onClose={() => setCreating(false)} onSaved={() => { setCreating(false); setRefresh(value => value + 1); flash("HR calendar event created and audited."); }} />}
  </>;
}

function CalendarMetric({ label, value, icon, tone }: { label: string; value: number; icon: string; tone: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><span>{label}</span><strong>{value}</strong><small>Selected calendar period</small></div>; }
function CalendarForm({ businessHeadId, onClose, onSaved }: { businessHeadId: string; onClose: () => void; onSaved: () => void }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await bodyData(await fetch("/api/calendar", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ businessHeadId: businessHeadId === "all" ? null : businessHeadId, eventType: form.get("eventType"), title: form.get("title"), eventDate: form.get("eventDate"), reminderRules: [{ daysBefore: Number(form.get("daysBefore")), roles: ["HR_ADMIN", "HR_OPERATIONS"] }] }) })); onSaved(); } catch (submissionError) { setError((submissionError as Error).message); setBusy(false); } } return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="eyebrow">Calendar</span><h2>Add a custom event</h2></div><button onClick={onClose} aria-label="Close">×</button></div><form onSubmit={submit} className="form-grid"><label>Event type<select name="eventType" defaultValue="hr_event"><option value="hr_event">HR event</option><option value="policy_effective">Policy effective</option><option value="training_event">Training event</option><option value="compliance_due">Compliance due</option><option value="leadership_review">Leadership review</option></select></label><label>Date<input name="eventDate" type="date" required /></label><label className="span-two">Title<input name="title" required /></label><label>Remind HR (days before)<input name="daysBefore" type="number" min="0" max="365" defaultValue="7" required /></label>{error && <div className="form-error span-two">{error}</div>}<div className="modal-actions span-two"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Saving…" : "Create event"}</button></div></form></section></div>; }
