"use client";
/* Payroll records and calculation traces are permission-shaped by the server. */
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Head = { id: string; name: string };
type Tab = "runs" | "rules" | "statutory" | "tax" | "exports" | "sandbox";
type FormKind = "period" | "component" | "rule" | "statutory" | "export";

const friendly = (value: unknown) => String(value || "—").replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const dateOnly = (value: unknown) => value ? String(value).slice(0, 10) : "—";
const money = (value: unknown) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value || 0));
const statusClass = (value: unknown) => String(value || "open").toLowerCase().replaceAll("_", "-");

async function data(response: Response) {
  const body = await response.json().catch(() => null);
  if (!response.ok) throw new Error(body?.error?.message || "The payroll action could not be completed.");
  return body?.data;
}

export function PayrollWorkspace({ businessHeadId, head, heads, flash }: { businessHeadId: string; head: string; heads: Head[]; flash: (message: string) => void }) {
  const [tab, setTab] = useState<Tab>("runs"); const [busy, setBusy] = useState(true); const [refresh, setRefresh] = useState(0); const [form, setForm] = useState<FormKind | null>(null);
  const [periods, setPeriods] = useState<any[]>([]); const [rules, setRules] = useState<any[]>([]); const [components, setComponents] = useState<any[]>([]); const [statutory, setStatutory] = useState<any[]>([]); const [exports, setExports] = useState<any[]>([]); const [taxDeclarations,setTaxDeclarations]=useState<any[]>([]);
  const [selectedPeriod, setSelectedPeriod] = useState<string>(""); const [results, setResults] = useState<any[]>([]); const [sandbox, setSandbox] = useState<any>(null); const [sandboxBusy, setSandboxBusy] = useState(false);
  const scoped = useCallback((path: string) => businessHeadId === "all" ? path : `${path}${path.includes("?") ? "&" : "?"}businessHeadId=${encodeURIComponent(businessHeadId)}`, [businessHeadId]);

  const load = useCallback(async () => {
    setBusy(true);
    try {
      const [periodData, ruleData, componentData, statutoryData, exportData,taxData] = await Promise.all([
        fetch(scoped("/api/payroll/periods")).then(data), fetch(scoped("/api/payroll/rules")).then(data), fetch("/api/payroll/components").then(data), fetch(scoped("/api/payroll/statutory-rule-sets")).then(data), fetch(scoped("/api/payroll/exports")).then(data),fetch(scoped("/api/payroll/tax-declarations")).then(data),
      ]);
      setPeriods(periodData || []); setRules(ruleData || []); setComponents(componentData || []); setStatutory(statutoryData || []); setExports(exportData || []);setTaxDeclarations(taxData||[]);
      setSelectedPeriod(current => current && periodData?.some((period: any) => period.id === current) ? current : periodData?.[0]?.id || "");
    } catch (error) { flash((error as Error).message); } finally { setBusy(false); }
  }, [scoped, flash]);
  useEffect(() => { load(); }, [load, refresh]);
  useEffect(() => { if (!selectedPeriod) { setResults([]); return; } fetch(`/api/payroll/results?payrollPeriodId=${encodeURIComponent(selectedPeriod)}`).then(data).then(rows => setResults(rows || [])).catch(error => flash(error.message)); }, [selectedPeriod, refresh, flash]);

  const selected = periods.find(period => period.id === selectedPeriod);
  const currentRules = useMemo(() => {
    const byCode = new Map<string, any>();
    for (const rule of rules.filter(item => item.status === "approved").sort((a, b) => Number(b.version) - Number(a.version))) if (!byCode.has(rule.code)) byCode.set(rule.code, rule);
    return [...byCode.values()].sort((a, b) => Number(a.priority) - Number(b.priority));
  }, [rules]);
  const totals = useMemo(() => results.reduce((out, row) => ({ gross: out.gross + Number(row.gross_earnings || 0), deductions: out.deductions + Number(row.deductions || 0), net: out.net + Number(row.net_pay || 0) }), { gross: 0, deductions: 0, net: 0 }), [results]);

  async function post(path: string, payload: unknown) { await data(await fetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) })); setRefresh(value => value + 1); }
  async function advance(period: any) {
    let path = "/api/payroll/run"; let payload: any = { payrollPeriodId: period.id };
    if (["open", "inputs_pending", "validating", "calculated"].includes(period.status)) payload.action = "calculate";
    else if (period.status === "review") { path = "/api/payroll/approve"; payload = { payrollPeriodId: period.id, decision: "approve", reason: window.prompt("Approval reason:", "Payroll totals, variances and calculation traces reviewed") }; }
    else if (period.status === "approved") payload.action = "lock";
    else if (period.status === "locked") { const paymentReference = window.prompt("Bank/payment reference:"); if (!paymentReference) return; payload = { payrollPeriodId: period.id, action: "mark_paid", paymentReference }; }
    else return flash(`Payroll is already ${friendly(period.status).toLowerCase()}.`);
    if (payload.reason === null) return;
    try { await post(path, payload); flash("Payroll advanced with an audit entry."); } catch (error) { flash((error as Error).message); }
  }
  async function ruleAction(rule: any) {
    const decision = ["draft", "rejected"].includes(rule.status) ? "submit" : rule.status === "pending" ? "approve" : rule.status === "approved" ? "retire" : null;
    if (!decision) return flash(`Rule version is ${friendly(rule.status).toLowerCase()}.`);
    const reason = window.prompt(`Reason to ${decision} ${rule.code} v${rule.version}:`, decision === "approve" ? "Formula, scope and effective dates independently verified" : "Payroll rule version progressed"); if (!reason) return;
    try { await post(`/api/payroll/rules/${rule.id}/decision`, { decision, reason }); flash(`Payroll rule ${friendly(decision).toLowerCase()}d.`); } catch (error) { flash((error as Error).message); }
  }
  async function statutoryAction(rule: any) {
    const action = ["draft", "rejected"].includes(rule.status) ? "submit" : rule.status === "pending" ? "approve" : null;
    if (!action) return flash(`Statutory rule set is ${friendly(rule.status).toLowerCase()}.`);
    const reason = window.prompt(`Reason to ${action} ${rule.code} v${rule.version}:`, action === "approve" ? "Effective dates and adviser-reviewed configuration verified" : "Statutory configuration ready for review"); if (!reason) return;
    try { await post(`/api/payroll/statutory-rule-sets/${rule.id}/decision`, { action, reason }); flash(`Statutory rule set ${friendly(action).toLowerCase()}d.`); } catch (error) { flash((error as Error).message); }
  }
  async function exportAction(item: any) {
    if (item.status === "pending") { const decision = window.confirm(`Approve the ${friendly(item.export_type).toLowerCase()} export?`) ? "approve" : "reject"; const reason = window.prompt(`Reason to ${decision}:`, decision === "approve" ? "Payroll is locked and export purpose verified" : "Export request requires correction"); if (!reason) return; try { await post(`/api/payroll/exports/${item.id}/decision`, { decision, reason }); flash(`Export ${decision}d.`); } catch (error) { flash((error as Error).message); } return; }
    if (item.status === "approved") { try { const response = await fetch(`/api/payroll/exports/${item.id}/generate`, { method: "POST" }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.error?.message || "Export could not be generated."); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = item.file_name || `velite-${item.export_type}-${dateOnly(item.period_month).slice(0, 7)}.csv`; link.click(); URL.revokeObjectURL(url); setRefresh(value => value + 1); flash("Controlled payroll export downloaded and checksummed."); } catch (error) { flash((error as Error).message); } return; }
    flash(`This export is ${friendly(item.status).toLowerCase()}.`);
  }
  async function taxAction(item:any){if(item.status!=="pending")return flash(`Declaration is ${friendly(item.status).toLowerCase()}.`);const decision=window.confirm(`Approve ${item.employee_name}'s ${item.financial_year} declaration?`)?"approve":"reject";const reason=window.prompt(`Reason to ${decision}:`,decision==="approve"?"Declaration totals and attached proofs independently reviewed":"Declaration or proofs require correction");if(!reason)return;const proofDecisions=Object.fromEntries((item.proofs||[]).map((proof:any)=>[proof.id,decision==="approve"?"approved":"rejected"]));try{await post(`/api/payroll/tax-declarations/${item.id}/decision`,{decision,reason,proofDecisions});flash(`Tax declaration ${decision}d.`)}catch(error){flash((error as Error).message)}}
  async function runSandbox(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSandboxBusy(true); const formData = new FormData(event.currentTarget);
    const context = { CALENDAR_DAYS: Number(formData.get("calendarDays")), DIVISOR_DAYS: Number(formData.get("divisorDays")), UNPAID_DAYS: Number(formData.get("unpaidDays")), PAYABLE_DAYS: Number(formData.get("calendarDays")) - Number(formData.get("unpaidDays")), MONTHLY_BASIC: Number(formData.get("monthlyBasic")), MONTHLY_ALLOWANCES: Number(formData.get("monthlyAllowances")), OVERTIME_HOURS: Number(formData.get("overtimeHours")), OVERTIME_RATE: Number(formData.get("overtimeRate")), ADVANCE_ADJUSTED: Number(formData.get("advanceAdjusted")), ADVANCE_BALANCE: Number(formData.get("advanceBalance")), OTHER_DEDUCTIONS_INPUT: Number(formData.get("otherDeductions")), ONE_TIME_EARNINGS_INPUT: Number(formData.get("oneTimeEarnings")) };
    const mapped = currentRules.map(rule => ({ code: rule.code, name: rule.name, category: rule.category, priority: Number(rule.priority), ...(rule.conditions && Object.keys(rule.conditions).length ? { condition: rule.conditions } : {}), formula: rule.formula, rounding: rule.rounding_method }));
    try { setSandbox(await data(await fetch("/api/payroll/calculate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ businessHeadId: businessHeadId === "all" ? null : businessHeadId, context, ...(mapped.length ? { rules: mapped } : {}) }) }))); } catch (error) { flash((error as Error).message); } finally { setSandboxBusy(false); }
  }

  return <>
    <div className="page-head"><div><span className="eyebrow">Salary</span><h1>Salary</h1><p>{head} · Start the month, check each person’s salary, get it approved, then pay. One person prepares and a different person approves.</p></div><button className="primary" onClick={() => setForm("period")}>＋ Start a salary month</button></div>
    <div className="metrics compact"><PayrollMetric label="SALARY MONTHS" value={periods.length} note="Salary months started" icon="□" tone="purple" /><PayrollMetric label="SALARY RULES IN USE" value={currentRules.length} note={`${rules.length} total versions`} icon="✓" tone="green" /><PayrollMetric label="TAKE-HOME PAY" value={money(totals.net)} note={`${results.length} staff paid`} icon="₹" tone="blue" /><PayrollMetric label="BANK FILES WAITING" value={exports.filter(item => ["pending", "approved"].includes(item.status)).length} note="Waiting for approval" icon="!" tone="orange" /></div>
    <section className="panel payroll-tabs"><nav>{(["runs", "rules", "statutory", "tax", "exports", "sandbox"] as Tab[]).map(item => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item === "runs" ? "Salary months" : item === "sandbox" ? "Test a rule" : item==="tax"?"Tax declarations":item==="rules"?"Salary rules":item==="statutory"?"PF, ESI & deductions":item==="exports"?"Bank & other files":friendly(item)}</button>)}</nav><div>{tab === "rules" && <><button className="secondary" onClick={() => setForm("component")}>Add salary component</button><button className="primary" onClick={() => setForm("rule")}>＋ New rule version</button></>}{tab === "statutory" && <button className="primary" onClick={() => setForm("statutory")}>＋ New statutory version</button>}{tab === "exports" && <button className="primary" disabled={!selected || !["locked", "paid"].includes(selected.status)} onClick={() => setForm("export")}>＋ Request export</button>}</div></section>
    {busy ? <section className="panel loading-panel">Loading payroll controls…</section> : <>
      {tab === "runs" && <div className="payroll-control-grid"><section className="panel payroll-period-list"><div className="panel-head padded"><div><h2>Salary months</h2><p>Choose a month to see each person’s salary</p></div></div>{periods.map(period => <button key={period.id} className={selectedPeriod === period.id ? "active" : ""} onClick={() => setSelectedPeriod(period.id)}><div><strong>{period.business_head}</strong><span>{dateOnly(period.period_month).slice(0, 7)} · pay {dateOnly(period.pay_date)}</span></div><b>{money(period.total_net_pay)}</b><em className={`status ${statusClass(period.status)}`}>{friendly(period.status)}</em></button>)}{!periods.length && <div className="empty-state padded">No salary month has been started yet.</div>}</section>
        <section className="panel payroll-run-card"><div className="panel-head padded"><div><h2>{selected ? `${selected.business_head} · ${dateOnly(selected.period_month).slice(0, 7)}` : "Choose a salary month"}</h2><p>{selected ? `${selected.result_count} result(s) · attendance cut-off ${dateOnly(selected.attendance_cutoff)}` : "The steps — prepare, check, approve, pay — will appear here."}</p></div>{selected && <button className="primary" onClick={() => advance(selected)}>{nextAction(selected.status)}</button>}</div>{selected && <><div className="run-steps payroll-run-steps">{["Inputs", "Calculate", "Reviewer", "Finance", "Lock", "Pay"].map((step, index) => <span key={step} className={index <= progress(selected.status) ? "done" : ""}><b>{index + 1}</b><small>{step}</small></span>)}</div><div className="payroll-total-cards"><div><span>GROSS</span><strong>{money(totals.gross)}</strong></div><div><span>DEDUCTIONS</span><strong>{money(totals.deductions)}</strong></div><div><span>NET PAYABLE</span><strong>{money(totals.net)}</strong></div></div></>}</section></div>}
      {tab === "runs" && selected && <section className="panel table-panel payroll-results"><div className="panel-head padded"><div><h2>Employee payroll register</h2><p>Attendance, advances and net payable are read from each immutable calculation trace</p></div></div><div className="data-table"><div className="tr th"><span>EMPLOYEE</span><span>MONTH DAYS</span><span>ABSENT</span><span>ADVANCE</span><span>ADJUSTED</span><span>BALANCE</span><span>NET PAYABLE</span></div>{results.map(row => { const context = row.calculation_trace?.context || {}; return <div className="tr" key={row.id}><span><b>{row.employee_name}<small>{row.employee_code} · {row.position}</small></b></span><span>{row.calendar_days}</span><span>{row.absent_days}</span><span>{money(context.ADVANCE_BALANCE)}</span><span>{money(context.ADVANCE_ADJUSTED)}</span><span>{money(Math.max(0, Number(context.ADVANCE_BALANCE || 0) - Number(context.ADVANCE_ADJUSTED || 0)))}</span><span><b>{money(row.net_pay)}</b></span></div>; })}</div>{!results.length && <div className="empty-state padded">Calculate this period to create employee results.</div>}</section>}
      {tab === "rules" && <div className="grid halves"><section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Salary components</h2><p>Earnings, deductions, reimbursements and employer contributions</p></div></div>{components.map((component, index) => <div className="payroll-component" key={component.id}><i>{index + 1}</i><div><strong>{component.code} · {component.name}</strong><small>{friendly(component.category)} · {component.taxable ? "taxable" : "non-taxable"}</small></div></div>)}</section><section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Salary rules</h2><p>Click a rule to send it for approval, or approve it</p></div></div>{rules.map((rule, index) => <button key={rule.id} onClick={() => ruleAction(rule)}><i>{index + 1}</i><div><b>{rule.code} v{rule.version} · {rule.name}</b><span>{rule.component_name || "Calculation"} · priority {rule.priority} · {dateOnly(rule.effective_from)} to {dateOnly(rule.effective_to)}</span></div><em className={`status ${statusClass(rule.status)}`}>{friendly(rule.status)}</em><strong>›</strong></button>)}</section></div>}
      {tab === "statutory" && <section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Statutory and final-settlement rule sets</h2><p>Rates remain effective-dated and must be adviser-reviewed before approval</p></div></div>{statutory.map((rule, index) => <button key={rule.id} onClick={() => statutoryAction(rule)}><i>{index + 1}</i><div><b>{rule.code} v{rule.version} · {rule.name}</b><span>{rule.business_head || "All Velite"} · effective {dateOnly(rule.effective_from)} to {dateOnly(rule.effective_to)} · maker {rule.created_by_name}</span></div><em className={`status ${statusClass(rule.status)}`}>{friendly(rule.status)}</em><strong>›</strong></button>)}{!statutory.length && <div className="empty-state padded">No statutory rule-set version exists.</div>}</section>}
      {tab === "tax" && <section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Employee tax declarations</h2><p>Regime selection, declared deductions and supporting proofs</p></div></div>{taxDeclarations.map((item,index)=><button key={item.id} onClick={()=>taxAction(item)}><i>{index+1}</i><div><b>{item.employee_name} · {item.financial_year}</b><span>{item.employee_code} · {friendly(item.regime)} regime · {item.proof_count} proof(s) · {money(item.proof_total)}</span></div><em className={`status ${statusClass(item.status)}`}>{friendly(item.status)}</em><strong>›</strong></button>)}{!taxDeclarations.length&&<div className="empty-state padded">No employee tax declarations are in this scope.</div>}</section>}
      {tab === "exports" && <section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Controlled payroll exports</h2><p>Requester, approver and generator must satisfy independent-control rules</p></div></div>{exports.map((item, index) => <button key={item.id} onClick={() => exportAction(item)}><i>{index + 1}</i><div><b>{friendly(item.export_type)} · {item.business_head}</b><span>{dateOnly(item.period_month).slice(0, 7)} · requested by {item.requested_by_name} · {item.row_count ? `${item.row_count} rows` : "not generated"}</span></div><em className={`status ${statusClass(item.status)}`}>{friendly(item.status)}</em><strong>›</strong></button>)}{!exports.length && <div className="empty-state padded">No controlled export has been requested.</div>}</section>}
      {tab === "sandbox" && <div className="payroll-sandbox"><section className="panel"><div className="panel-head padded"><div><h2>Test rules before payroll</h2><p>Uses {currentRules.length ? `${currentRules.length} current approved rule(s)` : "the safe standard monthly rules"}; no employee or payroll record is changed</p></div></div><form className="sandbox-form" onSubmit={runSandbox}><label>Calendar days<input name="calendarDays" type="number" min="1" defaultValue="31" required /></label><label>Salary divisor<input name="divisorDays" type="number" min="1" defaultValue="31" required /></label><label>Unpaid / absent days<input name="unpaidDays" type="number" min="0" step="0.5" defaultValue="1" required /></label><label>Monthly basic<input name="monthlyBasic" type="number" min="0" defaultValue="31000" required /></label><label>Monthly allowances<input name="monthlyAllowances" type="number" min="0" defaultValue="15500" required /></label><label>Overtime hours<input name="overtimeHours" type="number" min="0" step="0.25" defaultValue="2" /></label><label>Overtime rate<input name="overtimeRate" type="number" min="0" defaultValue="200" /></label><label>Advance balance<input name="advanceBalance" type="number" min="0" defaultValue="3000" /></label><label>Advance adjusted<input name="advanceAdjusted" type="number" min="0" defaultValue="3000" /></label><label>Other deductions<input name="otherDeductions" type="number" min="0" defaultValue="500" /></label><label>One-time earnings<input name="oneTimeEarnings" type="number" min="0" defaultValue="0" /></label><button className="primary" disabled={sandboxBusy}>{sandboxBusy ? "Calculating…" : "Run safe calculation"}</button></form></section><section className="panel sandbox-result"><div className="panel-head padded"><div><h2>Sandbox result</h2><p>Every amount shows the variables it used</p></div></div>{sandbox ? <><div className="payroll-total-cards"><div><span>GROSS</span><strong>{money(sandbox.grossEarnings)}</strong></div><div><span>DEDUCTIONS</span><strong>{money(sandbox.deductions)}</strong></div><div><span>NET PAYABLE</span><strong>{money(sandbox.netPay)}</strong></div></div><div className="sandbox-lines">{sandbox.lines?.map((line: any) => <div key={line.code}><div><strong>{line.name}</strong><small>{line.code} · {friendly(line.category)} · inputs {line.inputs?.join(", ") || "fixed"}</small></div><b>{money(line.amount)}</b></div>)}</div></> : <div className="empty-state padded">Enter a sample salary and run the sandbox.</div>}</section></div>}
    </>}
    {form && <PayrollForm kind={form} selectedHead={businessHeadId} heads={heads} components={components} periods={periods} selectedPeriod={selectedPeriod} onClose={() => setForm(null)} onSaved={() => { setForm(null); setRefresh(value => value + 1); flash("Payroll configuration saved with an audit entry."); }} />}
  </>;
}

function nextAction(status: string) { if (["open", "inputs_pending", "validating", "calculated"].includes(status)) return "Calculate payroll"; if (status === "review") return "Record next approval"; if (status === "approved") return "Lock payroll"; if (status === "locked") return "Mark paid"; return friendly(status); }
function progress(status: string) { return ({ open: 0, inputs_pending: 0, validating: 1, calculated: 1, review: 2, approved: 3, locked: 4, paid: 5 } as Record<string, number>)[status] ?? 0; }
function PayrollMetric({ label, value, note, icon, tone }: { label: string; value: string | number; note: string; icon: string; tone: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }

function PayrollForm({ kind, selectedHead, heads, components, periods, selectedPeriod, onClose, onSaved }: { kind: FormKind; selectedHead: string; heads: Head[]; components: any[]; periods: any[]; selectedPeriod: string; onClose: () => void; onSaved: () => void }) {
  const [headId, setHeadId] = useState(selectedHead === "all" ? heads[0]?.id || "" : selectedHead); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const month = new Date().toISOString().slice(0, 7); const today = new Date().toISOString().slice(0, 10);
  const titles: Record<FormKind, string> = { period: "Start a salary month", component: "Add salary component", rule: "Create payroll rule version", statutory: "Create statutory rule-set version", export: "Request controlled payroll export" };
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); const values = new FormData(event.currentTarget); let path = ""; let payload: any = {};
    if (kind === "period") { path = "/api/payroll/periods"; payload = { businessHeadId: headId, periodMonth: `${values.get("periodMonth")}-01`, attendanceCutoff: values.get("attendanceCutoff"), payDate: values.get("payDate") }; }
    if (kind === "component") { path = "/api/payroll/components"; payload = { code: String(values.get("code") || "").toUpperCase(), name: values.get("name"), category: values.get("category"), taxable: values.get("taxable") === "on" }; }
    if (kind === "rule") { path = "/api/payroll/rules"; const preset = values.get("preset"); const variable = String(values.get("variable") || "MONTHLY_BASIC").toUpperCase(); const numeric = Number(values.get("amount") || 0); let formula: any = { var: variable }; if (preset === "fixed") formula = numeric; if (preset === "percentage") formula = { multiply: [{ var: variable }, numeric / 100] }; if (preset === "prorated") formula = { multiply: [{ divide: [{ var: variable }, { var: "DIVISOR_DAYS" }] }, { var: "PAYABLE_DAYS" }] }; if (preset === "overtime") formula = { multiply: [{ var: "OVERTIME_HOURS" }, { var: "OVERTIME_RATE" }] }; payload = { code: String(values.get("code") || "").toUpperCase(), name: values.get("name"), businessHeadId: values.get("global") === "on" ? null : headId, componentId: values.get("componentId"), priority: Number(values.get("priority")), conditions: {}, formula, roundingMethod: values.get("roundingMethod"), effectiveFrom: values.get("effectiveFrom"), effectiveTo: values.get("effectiveTo") || null, changeReason: values.get("changeReason") }; }
    if (kind === "statutory") { path = "/api/payroll/statutory-rule-sets"; const codes = String(values.get("outputCodes") || "").split(",").map(item => item.trim().toUpperCase()).filter(Boolean); payload = { businessHeadId: values.get("global") === "on" ? null : headId, code: String(values.get("code") || "").toUpperCase(), name: values.get("name"), configuration: { outputGroups: { statutory: codes.length ? codes : ["STATUTORY_OUTPUT"] }, notes: values.get("notes") || undefined }, effectiveFrom: values.get("effectiveFrom"), effectiveTo: values.get("effectiveTo") || null, changeReason: values.get("changeReason") }; }
    if (kind === "export") { path = "/api/payroll/exports"; payload = { payrollPeriodId: values.get("payrollPeriodId"), exportType: values.get("exportType"), reason: values.get("reason") }; }
    try { await data(await fetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) })); onSaved(); } catch (submissionError) { setError((submissionError as Error).message); setBusy(false); }
  }
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="eyebrow">Salary</span><h2>{titles[kind]}</h2></div><button onClick={onClose} aria-label="Close">×</button></div><form className="form-grid" onSubmit={submit}>
    {["period", "rule", "statutory"].includes(kind) && <label className="span-two">Business head<select value={headId} onChange={event => setHeadId(event.target.value)} required>{heads.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
    {kind === "period" && <><label>Salary month<input name="periodMonth" type="month" defaultValue={month} required /></label><label>Attendance cut-off<input name="attendanceCutoff" type="date" required /></label><label>Pay date<input name="payDate" type="date" required /></label><div className="form-hint">Attendance must be reviewed and locked before calculation.</div></>}
    {kind === "component" && <><label>Component code<input name="code" placeholder="HOUSE_RENT_ALLOWANCE" pattern="[A-Za-z][A-Za-z0-9_]+" required /></label><label>Name<input name="name" placeholder="House rent allowance" required /></label><label>Category<select name="category"><option value="earning">Earning</option><option value="deduction">Deduction</option><option value="employer_contribution">Employer contribution</option><option value="reimbursement">Reimbursement</option></select></label><label className="check-label"><input name="taxable" type="checkbox" defaultChecked /> Taxable component</label></>}
    {kind === "rule" && <><label>Rule code<input name="code" placeholder="EARNED_BASIC" pattern="[A-Za-z][A-Za-z0-9_]+" required /></label><label>Rule name<input name="name" placeholder="Earned basic salary" required /></label><label>Salary component<select name="componentId" required>{components.map(item => <option value={item.id} key={item.id}>{item.name} · {friendly(item.category)}</option>)}</select></label><label>Priority<input name="priority" type="number" min="1" max="10000" defaultValue="100" required /></label><label>Calculation<select name="preset" defaultValue="prorated"><option value="prorated">Prorate a monthly value by payable days</option><option value="percentage">Percentage of a value</option><option value="input">Use an input value</option><option value="fixed">Fixed amount</option><option value="overtime">Overtime hours × rate</option></select></label><label>Input variable<input name="variable" defaultValue="MONTHLY_BASIC" pattern="[A-Z][A-Z0-9_]*" required /></label><label>Amount / percentage<input name="amount" type="number" step="0.0001" defaultValue="0" /></label><label>Rounding<select name="roundingMethod" defaultValue="nearest_rupee"><option value="nearest_rupee">Nearest rupee</option><option value="none">Two decimals</option><option value="up">Round up</option><option value="down">Round down</option></select></label><label>Effective from<input name="effectiveFrom" type="date" defaultValue={today} required /></label><label>Effective to<input name="effectiveTo" type="date" /></label><label className="check-label span-two"><input name="global" type="checkbox" /> Apply across all Velite business heads</label><label className="span-two">Change reason<input name="changeReason" placeholder="Why this version is required" required /></label><div className="form-hint span-two">Saving creates a draft immutable version. A different authorised user must approve it before payroll can use it.</div></>}
    {kind === "statutory" && <><label>Rule-set code<input name="code" placeholder="PF_2026" pattern="[A-Za-z][A-Za-z0-9_]+" required /></label><label>Name<input name="name" placeholder="Provident Fund 2026" required /></label><label>Effective from<input name="effectiveFrom" type="date" defaultValue={today} required /></label><label>Effective to<input name="effectiveTo" type="date" /></label><label className="span-two">Output component codes<input name="outputCodes" placeholder="EMPLOYEE_PF, EMPLOYER_PF" required /></label><label className="span-two">Configuration notes<input name="notes" placeholder="Applicability, ceiling, adviser reference and exceptions" /></label><label className="check-label span-two"><input name="global" type="checkbox" /> Apply across all Velite business heads</label><label className="span-two">Change reason<input name="changeReason" required /></label><div className="form-hint span-two">Legal rates are deliberately configuration, not permanent code. Obtain payroll/legal adviser review before approval.</div></>}
    {kind === "export" && <><label className="span-two">Locked payroll period<select name="payrollPeriodId" defaultValue={selectedPeriod} required>{periods.filter(period => ["locked", "paid"].includes(period.status)).map(period => <option value={period.id} key={period.id}>{period.business_head} · {dateOnly(period.period_month).slice(0, 7)}</option>)}</select></label><label>Export type<select name="exportType"><option value="bank">Bank payment advice</option><option value="accounting">Accounting journal</option><option value="statutory">Statutory register</option><option value="payroll_register">Payroll register</option></select></label><label className="span-two">Business reason<input name="reason" required /></label></>}
    {error && <div className="form-error span-two">{error}</div>}<div className="modal-actions span-two"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy || (["period", "rule", "statutory"].includes(kind) && !headId)}>{busy ? "Saving…" : "Save and continue"}</button></div>
  </form></section></div>;
}
