"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { FormEvent, useCallback, useEffect, useState } from "react";

type Head = { id: string; name: string };
type Person = { id: string; name: string; code: string; role: string; dept: string };
type FormKind = "cycle" | "goal" | "review" | "calibration";

const label = (value: unknown) => String(value || "open").replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const tone = (value: unknown) => String(value || "open").toLowerCase().replaceAll("_", "-");

async function data(response: Response) {
  const body = await response.json().catch(() => null);
  if (!response.ok) throw new Error(body?.error?.message || "The performance action could not be completed.");
  return body?.data;
}

export function PerformanceWorkspace({ businessHeadId, head, heads, people, flash }: { businessHeadId: string; head: string; heads: Head[]; people: Person[]; flash: (message: string) => void }) {
  const [cycles, setCycles] = useState<any[]>([]); const [goals, setGoals] = useState<any[]>([]); const [reviews, setReviews] = useState<any[]>([]); const [calibrations, setCalibrations] = useState<any[]>([]);
  const [busy, setBusy] = useState(true); const [form, setForm] = useState<FormKind | null>(null); const [refresh, setRefresh] = useState(0);
  const scope = useCallback((path: string) => businessHeadId === "all" ? path : `${path}${path.includes("?") ? "&" : "?"}businessHeadId=${encodeURIComponent(businessHeadId)}`, [businessHeadId]);
  useEffect(() => { let closed = false; Promise.all([
    fetch(scope("/api/performance/cycles")).then(data), fetch(scope("/api/performance/goals")).then(data), fetch(scope("/api/performance/reviews")).then(data), fetch(scope("/api/performance/calibrations")).then(data),
  ]).then(([cycleRows, goalRows, reviewRows, calibrationRows]) => { if (!closed) { setCycles(cycleRows || []); setGoals(goalRows || []); setReviews(reviewRows || []); setCalibrations(calibrationRows || []); } }).catch(error => flash(error.message)).finally(() => { if (!closed) setBusy(false); }); return () => { closed = true; }; }, [scope, refresh, flash]);

  const completed = reviews.filter(row => row.status === "completed").length; const progress = reviews.length ? Math.round(completed / reviews.length * 100) : 0;
  async function cycleAction(cycle: any) { const action = cycle.status === "draft" ? "launch" : cycle.status === "pending" ? "complete" : cycle.status === "completed" ? "reopen" : "reopen"; const reason = window.prompt(`Reason to ${action} ${cycle.name}:`, `${label(action)} appraisal cycle`); if (!reason) return; try { await data(await fetch(`/api/performance/cycles/${cycle.id}/transition`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, reason }) })); setRefresh(value => value + 1); flash(`Appraisal cycle ${label(action).toLowerCase()}ed.`); } catch (error) { flash((error as Error).message); } }
  async function goalAction(goal: any) { const progressValue = window.prompt(`Progress for ${goal.employee_name}'s goal (0–100):`, String(goal.progress)); if (progressValue === null) return; const progressNumber = Number(progressValue); if (!Number.isFinite(progressNumber)) return flash("Enter a valid progress percentage."); const reason = window.prompt("Progress note:", "Manager progress review"); if (!reason) return; try { await data(await fetch(`/api/performance/goals/${goal.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ progress: progressNumber, status: progressNumber === 100 ? "completed" : "active", reason }) })); setRefresh(value => value + 1); flash("Goal progress saved and audited."); } catch (error) { flash((error as Error).message); } }
  return <>
    <div className="page-head"><div><span className="eyebrow">Appraisals</span><h1>Appraisals</h1><p>{head} · Set goals, review how people are doing, and plan their growth.</p></div><button className="primary" onClick={() => setForm("cycle")}>＋ Start an appraisal round</button></div>
    <div className="metrics compact"><Metric label="CYCLES" value={cycles.length} icon="☆" tone="purple" /><Metric label="WEIGHTED GOALS" value={goals.length} icon="◎" tone="blue" /><Metric label="REVIEWS COMPLETE" value={completed} icon="✓" tone="green" /><Metric label="COMPLETION" value={`${progress}%`} icon="◷" tone="orange" /></div>
    <section className="panel operations-toolbar"><div><strong>Appraisal controls</strong><span>Department scope and rating evidence are enforced by the server</span></div><div><button className="secondary" onClick={() => setForm("goal")}>Assign goal</button><button className="secondary" onClick={() => setForm("review")}>Record review</button><button className="secondary" onClick={() => setForm("calibration")}>Schedule calibration</button></div></section>
    <div className="grid halves"><section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Review cycles</h2><p>Click a cycle to launch, complete or reopen it</p></div></div>{cycles.map((cycle, index) => <button key={cycle.id} onClick={() => cycleAction(cycle)}><i>{index + 1}</i><div><b>{cycle.name}</b><span>{cycle.department || cycle.business_head || "All Velite"} · {String(cycle.start_date).slice(0, 10)} to {String(cycle.end_date).slice(0, 10)} · {cycle.completed_count}/{cycle.review_count} reviews</span></div><em className={`status ${tone(cycle.status)}`}>{label(cycle.status)}</em><strong>›</strong></button>)}{!busy && !cycles.length && <div className="empty-state padded">No appraisal cycles in this view.</div>}</section>
      <section className="panel worklist operations-list"><div className="panel-head padded"><div><h2>Calibration</h2><p>Department-wise consistency and locked decisions</p></div></div>{calibrations.map((session, index) => <button key={session.id} onClick={() => flash(`${session.department} calibration opened.`)}><i>{index + 1}</i><div><b>{session.department} · {session.cycle_name}</b><span>{session.scheduled_at ? new Date(session.scheduled_at).toLocaleString("en-IN") : "Schedule pending"}{session.locked_at ? " · decisions locked" : ""}</span></div><em className={`status ${tone(session.status)}`}>{label(session.status)}</em><strong>›</strong></button>)}{!busy && !calibrations.length && <div className="empty-state padded">No calibration sessions scheduled.</div>}</section></div>
    <section className="panel table-panel"><div className="panel-head padded"><div><h2>Employee goals</h2><p>Click a goal to record manager-reviewed progress</p></div></div><div className="data-table performance-table"><div className="tr th"><span>EMPLOYEE</span><span>GOAL</span><span>CYCLE</span><span>WEIGHT</span><span>PROGRESS</span><span>STATUS</span></div>{goals.map(goal => <button className="tr" key={goal.id} onClick={() => goalAction(goal)}><span><b>{goal.employee_name}<small>{goal.employee_code}</small></b></span><span>{goal.title}</span><span>{goal.cycle_name}</span><span>{goal.weight}%</span><span><b>{goal.progress}%</b></span><span><em className={`status ${tone(goal.status)}`}>{label(goal.status)}</em></span></button>)}</div>{!busy && !goals.length && <div className="empty-state padded">No weighted goals assigned.</div>}</section>
    <section className="panel table-panel performance-reviews"><div className="panel-head padded"><div><h2>Review evidence</h2><p>Self, manager, peer and 360-degree submissions</p></div></div><div className="data-table performance-table"><div className="tr th"><span>EMPLOYEE</span><span>REVIEWER</span><span>TYPE</span><span>RATING</span><span>SUBMITTED</span><span>STATUS</span></div>{reviews.map(review => <div className="tr" key={review.id}><span>{review.employee_name}</span><span>{review.reviewer_name}</span><span>{label(review.review_type)}</span><span>{review.overall_rating ?? "—"}</span><span>{review.submitted_at ? new Date(review.submitted_at).toLocaleDateString("en-IN") : "Draft"}</span><span><em className={`status ${tone(review.status)}`}>{label(review.status)}</em></span></div>)}</div></section>
    {form && <PerformanceForm kind={form} activeHead={businessHeadId} heads={heads} people={people} cycles={cycles} onClose={() => setForm(null)} onSaved={() => { setForm(null); setRefresh(value => value + 1); flash("Performance record saved with an audit entry."); }} />}
  </>;
}

function Metric({ label: metricLabel, value, icon, tone: metricTone }: { label: string; value: string | number; icon: string; tone: string }) { return <div className="metric"><div className={`metric-icon ${metricTone}`}>{icon}</div><span>{metricLabel}</span><strong>{value}</strong><small>Current authorised scope</small></div>; }

function PerformanceForm({ kind, activeHead, heads, people, cycles, onClose, onSaved }: { kind: FormKind; activeHead: string; heads: Head[]; people: Person[]; cycles: any[]; onClose: () => void; onSaved: () => void }) {
  const [headId, setHeadId] = useState(activeHead === "all" ? heads[0]?.id || "" : activeHead); const [departments, setDepartments] = useState<{ id: string; name: string }[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (headId) fetch(`/api/departments?businessHeadId=${encodeURIComponent(headId)}`).then(response => response.ok ? response.json() : ({ data: [] })).then(body => setDepartments(body.data || [])); }, [headId]);
  const titles: Record<FormKind, string> = { cycle: "Create appraisal cycle", goal: "Assign weighted goal", review: "Record performance review", calibration: "Schedule department calibration" };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); let endpoint = ""; let payload: any = {};
    if (kind === "cycle") { endpoint = "/api/performance/cycles"; payload = { businessHeadId: headId, departmentId: form.get("departmentId") || null, name: form.get("name"), startDate: form.get("startDate"), endDate: form.get("endDate"), template: { ratingScale: [{ value: 1, label: "Needs improvement" }, { value: 2, label: "Developing" }, { value: 3, label: "Meets expectations" }, { value: 4, label: "Exceeds expectations" }, { value: 5, label: "Exceptional" }], sections: [{ code: "RESULTS", name: "Business results", weight: 50 }, { code: "COMPETENCIES", name: "Role competencies", weight: 30 }, { code: "VALUES", name: "Velite values", weight: 20 }] } }; }
    if (kind === "goal") { endpoint = "/api/performance/goals"; payload = { cycleId: form.get("cycleId"), employeeId: form.get("employeeId"), title: form.get("title"), description: form.get("description") || null, weight: Number(form.get("weight")), targetValue: form.get("targetValue") ? Number(form.get("targetValue")) : null }; }
    if (kind === "review") { endpoint = "/api/performance/reviews"; const rating = Number(form.get("overallRating")); payload = { cycleId: form.get("cycleId"), employeeId: form.get("employeeId"), reviewerId: form.get("reviewerId"), reviewType: form.get("reviewType"), ratings: { results: rating, competencies: rating, values: rating }, overallRating: rating, comments: form.get("comments") || null, submit: form.get("submit") === "on" }; }
    if (kind === "calibration") { endpoint = "/api/performance/calibrations"; const scheduled = String(form.get("scheduledAt") || ""); payload = { cycleId: form.get("cycleId"), departmentId: form.get("departmentId"), scheduledAt: scheduled ? new Date(scheduled).toISOString() : null, participants: [] }; }
    try { await data(await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) })); onSaved(); } catch (submissionError) { setError((submissionError as Error).message); setBusy(false); }
  }
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="eyebrow">PERFORMANCE WORKFLOW</span><h2>{titles[kind]}</h2></div><button onClick={onClose} aria-label="Close">×</button></div><form className="form-grid" onSubmit={submit}>
    {kind === "cycle" && <><label>Business head<select value={headId} onChange={event => setHeadId(event.target.value)}>{heads.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Department<select name="departmentId"><option value="">All departments</option>{departments.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="span-two">Cycle name<input name="name" placeholder="FY 2026 Annual Appraisal" required /></label><label>Starts<input name="startDate" type="date" required /></label><label>Ends<input name="endDate" type="date" required /></label><div className="form-hint span-two">Template: 50% results, 30% role competencies and 20% Velite values on a five-point scale.</div></>}
    {kind === "goal" && <><label className="span-two">Cycle<select name="cycleId" required>{cycles.filter(cycle => !["completed", "cancelled"].includes(cycle.status)).map(cycle => <option value={cycle.id} key={cycle.id}>{cycle.name} · {cycle.department || cycle.business_head || "All Velite"}</option>)}</select></label><label>Employee<select name="employeeId" required>{people.map(person => <option value={person.id} key={person.id}>{person.name} · {person.code}</option>)}</select></label><label>Weight (%)<input name="weight" type="number" min="1" max="100" defaultValue="25" required /></label><label className="span-two">Goal title<input name="title" required /></label><label className="span-two">Description<input name="description" /></label><label>Numeric target (optional)<input name="targetValue" type="number" step="0.01" /></label></>}
    {kind === "review" && <><label>Cycle<select name="cycleId" required>{cycles.map(cycle => <option value={cycle.id} key={cycle.id}>{cycle.name}</option>)}</select></label><label>Review type<select name="reviewType" defaultValue="manager"><option value="self">Self</option><option value="manager">Manager</option><option value="second_level">Second level</option><option value="peer">Peer</option><option value="direct_report">Direct report</option><option value="360">360 degree</option></select></label><label>Employee<select name="employeeId" required>{people.map(person => <option value={person.id} key={person.id}>{person.name} · {person.code}</option>)}</select></label><label>Reviewer<select name="reviewerId" required>{people.map(person => <option value={person.id} key={person.id}>{person.name} · {person.code}</option>)}</select></label><label>Overall rating (0–10)<input name="overallRating" type="number" min="0" max="10" step="0.1" required /></label><label className="check-label"><input name="submit" type="checkbox" /> Submit as final</label><label className="span-two">Evidence and comments<input name="comments" /></label></>}
    {kind === "calibration" && <><label>Cycle<select name="cycleId" required>{cycles.map(cycle => <option value={cycle.id} key={cycle.id}>{cycle.name}</option>)}</select></label><label>Department<select name="departmentId" required><option value="">Select department</option>{departments.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="span-two">Date and time<input name="scheduledAt" type="datetime-local" required /></label></>}
    {error && <div className="form-error span-two">{error}</div>}<div className="modal-actions span-two"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Saving…" : "Save and continue"}</button></div>
  </form></section></div>;
}
