import { z } from "zod";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { hasRoleForScope } from "@/lib/auth";
import { db } from "@/lib/database";

const schema=z.object({businessHeadId:z.uuid(),employeeId:z.uuid().nullable().optional(),category:z.string().min(2).max(80),subject:z.string().min(3).max(200),description:z.string().min(5).max(10000),confidential:z.boolean().default(false),priority:z.enum(['low','normal','high','urgent']).default('normal'),assignedTo:z.uuid().nullable().optional(),dueAt:z.iso.datetime().nullable().optional()});

export async function GET(request:Request){try{const u=new URL(request.url);const head=u.searchParams.get('businessHeadId');const status=u.searchParams.get('status');const user=await requireApiUser('helpdesk:read',head);if(user instanceof Response)return user;const confidential=hasRoleForScope(user,['HR_ADMIN','HR_OPERATIONS'],head);return ok(await db()`SELECT c.id,c.case_number,c.business_head_id,c.employee_id,c.category,c.subject,CASE WHEN c.confidential AND ${!confidential} THEN '[Confidential]' ELSE c.description END AS description,c.confidential,c.priority,c.status,c.assigned_to,c.due_at,c.resolved_at,c.created_at,b.name AS business_head,concat_ws(' ',e.first_name,e.last_name) AS employee_name FROM helpdesk_cases c JOIN business_heads b ON b.id=c.business_head_id LEFT JOIN employees e ON e.id=c.employee_id WHERE (${head}::uuid IS NULL OR c.business_head_id=${head}::uuid) AND (${status}::text IS NULL OR c.status=${status}) ORDER BY CASE c.priority WHEN 'urgent' THEN 1 WHEN 'high' THEN 2 WHEN 'normal' THEN 3 ELSE 4 END,c.due_at NULLS LAST`);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const user=await requireApiUser('helpdesk:write',input.businessHeadId);if(user instanceof Response)return user;const number=`HR-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const [row]=await db().begin(async tx=>{const rows=await tx`INSERT INTO helpdesk_cases (case_number,business_head_id,employee_id,category,subject,description,confidential,priority,assigned_to,due_at,created_by) VALUES (${number},${input.businessHeadId},${input.employeeId||null},${input.category},${input.subject},${input.description},${input.confidential},${input.priority},${input.assignedTo||null},${input.dueAt||null},${user.id}) RETURNING *`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'helpdesk.create','helpdesk_case',${rows[0].id},${input.businessHeadId},${JSON.stringify({id:rows[0].id,case_number:rows[0].case_number,category:rows[0].category,confidential:rows[0].confidential})}::jsonb,'Helpdesk case created')`;return rows;});return ok(row,{status:201});}catch(e){return apiError(e);}}
