import { createHash,randomBytes } from "node:crypto";
import { z } from "zod";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";

const permission=z.enum(['people:read','attendance:read','attendance:write','leave:read','recruitment:read','recruitment:write','documents:read','reports:read']);
const schema=z.object({name:z.string().min(3).max(120),permissions:z.array(permission).min(1).max(20),businessHeadId:z.uuid().nullable().optional(),expiresAt:z.iso.datetime().nullable().optional(),reason:z.string().min(5).max(1000)});
export async function GET(){try{const user=await requireApiUser('admin:users');if(user instanceof Response)return user;return ok(await db()`SELECT k.id,k.name,k.token_prefix,k.permissions,k.business_head_id,k.expires_at,k.last_used_at,k.revoked_at,k.created_at,b.name AS business_head,u.full_name AS created_by_name FROM api_keys k LEFT JOIN business_heads b ON b.id=k.business_head_id JOIN users u ON u.id=k.created_by ORDER BY k.created_at DESC`);}catch(error){return apiError(error);}}
export async function POST(request:Request){try{const input=schema.parse(await request.json());const user=await requireApiUser('admin:users');if(user instanceof Response)return user;const secret=`vel_${randomBytes(32).toString('base64url')}`;const hash=createHash('sha256').update(secret).digest('hex');const prefix=secret.slice(0,12);const [created]=await db().begin(async tx=>{const rows=await tx`INSERT INTO api_keys (name,token_hash,token_prefix,permissions,business_head_id,expires_at,created_by) VALUES (${input.name},${hash},${prefix},${JSON.stringify(input.permissions)}::jsonb,${input.businessHeadId||null},${input.expiresAt||null},${user.id}) RETURNING id,name,token_prefix,permissions,business_head_id,expires_at,created_at`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'api_key.create','api_key',${rows[0].id},${input.businessHeadId||null},${JSON.stringify(rows[0])}::jsonb,${input.reason})`;return rows;});return ok({apiKey:created,token:secret,warning:'Copy this token now. It will not be shown again.'},{status:201});}catch(error){return apiError(error);}}
