import { z } from "zod";
import { apiError, fail, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";
import { hashPassword } from "@/lib/password";

const roleSchema=z.object({code:z.enum(['SUPER_ADMIN','HR_ADMIN','HR_OPERATIONS','RECRUITER','MANAGER','DEPARTMENT_HEAD','PAYROLL_ADMIN','FINANCE_APPROVER','LEADERSHIP','AUDITOR','EMPLOYEE','IT_FACILITIES']),businessHeadId:z.uuid().nullable().optional(),departmentId:z.uuid().nullable().optional()})
  .refine(role=>role.code!=='SUPER_ADMIN'||(!role.businessHeadId&&!role.departmentId),{message:'Super administrators cannot be scope-limited'})
  .refine(role=>!role.departmentId||Boolean(role.businessHeadId),{message:'A department scope must include its business head'});
const schema=z.object({email:z.email(),fullName:z.string().min(2).max(120),temporaryPassword:z.string().min(12).max(128),roles:z.array(roleSchema).min(1).max(30)});
export async function GET(){try{const user=await requireApiUser('admin:users');if(user instanceof Response)return user;return ok(await db()`SELECT u.id,u.email,u.full_name,u.active,u.mfa_required,u.last_login_at,u.created_at,coalesce(jsonb_agg(jsonb_build_object('code',r.code,'name',r.name,'businessHeadId',ur.business_head_id,'departmentId',ur.department_id)) FILTER (WHERE r.id IS NOT NULL),'[]'::jsonb) AS roles FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id GROUP BY u.id ORDER BY u.full_name`);}catch(e){return apiError(e);}}
export async function POST(request:Request){try{const input=schema.parse(await request.json());const actor=await requireApiUser('admin:users');if(actor instanceof Response)return actor;const sql=db();for(const assignment of input.roles){if(assignment.departmentId){const [department]=await sql`SELECT business_head_id FROM departments WHERE id=${assignment.departmentId}`;if(!department)return fail('Department not found',404);if(assignment.businessHeadId&&department.business_head_id!==assignment.businessHeadId)return fail('Department does not belong to the selected business head',422);}}const password=await hashPassword(input.temporaryPassword);const [created]=await sql.begin(async tx=>{const rows=await tx`INSERT INTO users (email,password_hash,full_name,must_change_password) VALUES (${input.email.toLowerCase()},${password},${input.fullName},true) RETURNING id,email,full_name,active,created_at`;for(const assignment of input.roles){const [role]=await tx`SELECT id FROM roles WHERE code=${assignment.code}`;if(!role)throw new Error(`Missing seeded role ${assignment.code}`);await tx`INSERT INTO user_roles (user_id,role_id,business_head_id,department_id) VALUES (${rows[0].id},${role.id},${assignment.businessHeadId||null},${assignment.departmentId||null})`;}await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,after_data,reason) VALUES (${actor.id},'user.create','user',${rows[0].id},${JSON.stringify({email:rows[0].email,fullName:rows[0].full_name,roles:input.roles})}::jsonb,'Administrator provisioned user')`;return rows;});return ok(created,{status:201});}catch(e){return apiError(e);}}
