import { z } from "zod";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";

const schema=z.object({candidateId:z.uuid(),templateName:z.string().min(2).max(120),plannedJoiningDate:z.iso.date(),ownerId:z.uuid().nullable().optional(),tasks:z.array(z.object({title:z.string().min(2).max(200),category:z.string().min(2).max(60),assignedTo:z.uuid().nullable().optional(),dueDate:z.iso.date().nullable().optional()})).min(1).max(100)});

export async function GET(request:Request){try{const head=new URL(request.url).searchParams.get('businessHeadId');const user=await requireApiUser('onboarding:read',head);if(user instanceof Response)return user;return ok(await db()`SELECT o.*,c.full_name,c.position,c.business_head_id,b.name AS business_head,(SELECT count(*)::int FROM onboarding_tasks t WHERE t.onboarding_case_id=o.id) AS task_count,(SELECT count(*)::int FROM onboarding_tasks t WHERE t.onboarding_case_id=o.id AND t.status='completed') AS completed_tasks FROM onboarding_cases o JOIN candidates c ON c.id=o.candidate_id JOIN business_heads b ON b.id=c.business_head_id WHERE (${head}::uuid IS NULL OR c.business_head_id=${head}::uuid) ORDER BY o.planned_joining_date`);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const sql=db();const [candidate]=await sql<{business_head_id:string}[]>`SELECT business_head_id FROM candidates WHERE id=${input.candidateId}`;const user=await requireApiUser('onboarding:write',candidate?.business_head_id);if(user instanceof Response)return user;const [row]=await sql.begin(async tx=>{const rows=await tx`INSERT INTO onboarding_cases (candidate_id,template_name,planned_joining_date,owner_id) VALUES (${input.candidateId},${input.templateName},${input.plannedJoiningDate},${input.ownerId||user.id}) RETURNING *`;for(const task of input.tasks)await tx`INSERT INTO onboarding_tasks (onboarding_case_id,title,category,assigned_to,due_date) VALUES (${rows[0].id},${task.title},${task.category},${task.assignedTo||null},${task.dueDate||null})`;await tx`UPDATE candidates SET stage='hired',updated_at=now() WHERE id=${input.candidateId}`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'onboarding.start','onboarding_case',${rows[0].id},${candidate.business_head_id},${JSON.stringify(rows[0])}::jsonb,'Onboarding started')`;return rows;});return ok(row,{status:201});}catch(e){return apiError(e);}}
