import { z } from "zod";
import { db } from "@/lib/database";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { validateExpression, validateCondition } from "@/lib/payroll-engine";

const ruleSchema=z.object({code:z.string().min(2).max(40),name:z.string().min(2).max(120),businessHeadId:z.uuid().nullable().optional(),componentId:z.uuid().nullable().optional(),priority:z.number().int().min(1).max(10000).default(100),conditions:z.record(z.string(),z.unknown()).default({}),formula:z.record(z.string(),z.unknown()),roundingMethod:z.enum(['none','nearest_rupee','up','down']).default('nearest_rupee'),effectiveFrom:z.iso.date(),effectiveTo:z.iso.date().nullable().optional(),changeReason:z.string().min(5).max(500)}).refine(value=>!value.effectiveTo||value.effectiveTo>=value.effectiveFrom,{message:'Effective end cannot precede effective start'});

export async function GET(request:Request){try{const head=new URL(request.url).searchParams.get('businessHeadId');const user=await requireApiUser('payroll:read',head);if(user instanceof Response)return user;return ok(await db()`SELECT r.*,c.name AS component_name,c.category,b.name AS business_head FROM payroll_rules r LEFT JOIN salary_components c ON c.id=r.component_id LEFT JOIN business_heads b ON b.id=r.business_head_id WHERE (${head}::uuid IS NULL OR r.business_head_id=${head}::uuid OR r.business_head_id IS NULL) ORDER BY r.code,r.version DESC`);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=ruleSchema.parse(await request.json());validateExpression(input.formula);if(Object.keys(input.conditions).length)validateCondition(input.conditions);const user=await requireApiUser('payroll:write',input.businessHeadId);if(user instanceof Response)return user;const sql=db();const [row]=await sql.begin(async tx=>{const [latest]=await tx<{version:number}[]>`SELECT version FROM payroll_rules WHERE code=${input.code} ORDER BY version DESC LIMIT 1`;const version=(latest?.version||0)+1;const rows=await tx`INSERT INTO payroll_rules (code,name,business_head_id,component_id,version,priority,conditions,formula,rounding_method,effective_from,effective_to,change_reason,created_by) VALUES (${input.code},${input.name},${input.businessHeadId||null},${input.componentId||null},${version},${input.priority},${JSON.stringify(input.conditions)}::jsonb,${JSON.stringify(input.formula)}::jsonb,${input.roundingMethod},${input.effectiveFrom},${input.effectiveTo||null},${input.changeReason},${user.id}) RETURNING *`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'payroll_rule.create','payroll_rule',${rows[0].id},${input.businessHeadId||null},${JSON.stringify(rows[0])}::jsonb,${input.changeReason})`;return rows;});return ok(row,{status:201});}catch(e){return apiError(e);}}
