import { z } from "zod";
import { apiError, ok, requireApiUser } from "@/lib/api";
import { db } from "@/lib/database";

const schema=z.object({businessHeadId:z.uuid().nullable().optional(),employeeId:z.uuid().nullable().optional(),eventType:z.string().regex(/^[a-z][a-z0-9_]{1,59}$/),title:z.string().min(2).max(200),eventDate:z.iso.date(),reminderRules:z.array(z.object({daysBefore:z.number().int().min(0).max(365),roles:z.array(z.string().regex(/^[A-Z][A-Z0-9_]{1,49}$/)).max(20)})).max(20).default([])});

export async function GET(request:Request){try{const u=new URL(request.url);const head=u.searchParams.get('businessHeadId');const from=u.searchParams.get('from')||new Date().toISOString().slice(0,10);const to=u.searchParams.get('to')||new Date(Date.now()+90*86400000).toISOString().slice(0,10);const user=await requireApiUser('calendar:read',head);if(user instanceof Response)return user;return ok(await db()`SELECT c.*,concat_ws(' ',e.first_name,e.last_name) AS employee_name,b.name AS business_head FROM hr_calendar_events c LEFT JOIN employees e ON e.id=c.employee_id LEFT JOIN business_heads b ON b.id=c.business_head_id WHERE c.event_date BETWEEN ${from} AND ${to} AND (${head}::uuid IS NULL OR c.business_head_id=${head}::uuid OR c.business_head_id IS NULL) ORDER BY c.event_date`);}catch(e){return apiError(e);}}

export async function POST(request:Request){try{const input=schema.parse(await request.json());const sql=db();let resolvedHead=input.businessHeadId||null;if(input.employeeId){const [employee]=await sql<{business_head_id:string}[]>`SELECT business_head_id FROM employees WHERE id=${input.employeeId}`;if(!employee)return new Response(JSON.stringify({error:{message:'Employee not found'}}),{status:404,headers:{'content-type':'application/json'}});if(resolvedHead&&resolvedHead!==employee.business_head_id)return new Response(JSON.stringify({error:{message:'Employee and calendar event must belong to the same business head'}}),{status:422,headers:{'content-type':'application/json'}});resolvedHead=employee.business_head_id;}const user=await requireApiUser('calendar:write',resolvedHead);if(user instanceof Response)return user;const [row]=await sql.begin(async tx=>{const rows=await tx`INSERT INTO hr_calendar_events (business_head_id,employee_id,event_type,title,event_date,reminder_rules) VALUES (${resolvedHead},${input.employeeId||null},${input.eventType},${input.title},${input.eventDate},${JSON.stringify(input.reminderRules)}::jsonb) RETURNING *`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'calendar_event.create','hr_calendar_event',${rows[0].id},${resolvedHead},${JSON.stringify(rows[0])}::jsonb,'HR calendar event created')`;return rows;});return ok(row,{status:201});}catch(e){return apiError(e);}}
