import { z } from "zod";
import { apiError, fail, ok, requireAnyApiPermission } from "@/lib/api";
import { db } from "@/lib/database";
import { openJson, sealJson } from "@/lib/encryption";

const schema=z.object({bankDetails:z.object({accountHolder:z.string().min(2).max(160),bankName:z.string().min(2).max(160),accountNumber:z.string().min(4).max(40),ifsc:z.string().min(4).max(30)}).nullable().optional(),statutoryDetails:z.record(z.string(),z.string().max(160)).nullable().optional(),reason:z.string().min(3).max(1000)});
const masked=(value:string)=>value.length<=4?'•'.repeat(value.length):`${'•'.repeat(Math.min(8,value.length-4))}${value.slice(-4)}`;
function safeOpen(value:Uint8Array|null){if(!value)return null;return openJson<Record<string,string>>(value);}
function present(bank:Record<string,string>|null,statutory:Record<string,string>|null){return{bankDetails:bank?{accountHolder:bank.accountHolder,bankName:bank.bankName,accountNumber:masked(bank.accountNumber||''),ifsc:bank.ifsc}:null,statutoryDetails:statutory?Object.fromEntries(Object.entries(statutory).map(([key,value])=>[key,masked(value)])):null};}

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const sql=db();const [employee]=await sql<[{business_head_id:string;department_id:string|null;bank_details_encrypted:Uint8Array|null;statutory_details_encrypted:Uint8Array|null}]>`SELECT business_head_id,department_id,bank_details_encrypted,statutory_details_encrypted FROM employees WHERE id=${id}`;if(!employee)return fail('Employee not found',404);const user=await requireAnyApiPermission(['payroll:read','people:write'],employee.business_head_id,employee.department_id);if(user instanceof Response)return user;const data=present(safeOpen(employee.bank_details_encrypted),safeOpen(employee.statutory_details_encrypted));await sql`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,after_data,reason) VALUES (${user.id},'employee.sensitive_view','employee',${id},${employee.business_head_id},${JSON.stringify({masked:true,apiKeyId:user.apiKeyId||null})}::jsonb,'Masked bank and statutory details viewed')`;return ok(data);}catch(error){return apiError(error);}}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const input=schema.parse(await request.json());const sql=db();const [employee]=await sql`SELECT id,business_head_id,department_id,bank_details_encrypted,statutory_details_encrypted FROM employees WHERE id=${id}`;if(!employee)return fail('Employee not found',404);const user=await requireAnyApiPermission(['payroll:write','people:write'],employee.business_head_id,employee.department_id);if(user instanceof Response)return user;const before={hasBankDetails:Boolean(employee.bank_details_encrypted),hasStatutoryDetails:Boolean(employee.statutory_details_encrypted)};const [updated]=await sql.begin(async tx=>{const rows=await tx`UPDATE employees SET bank_details_encrypted=CASE WHEN ${input.bankDetails!==undefined} THEN ${input.bankDetails?sealJson(input.bankDetails):null} ELSE bank_details_encrypted END,statutory_details_encrypted=CASE WHEN ${input.statutoryDetails!==undefined} THEN ${input.statutoryDetails?sealJson(input.statutoryDetails):null} ELSE statutory_details_encrypted END,updated_at=now() WHERE id=${id} RETURNING id,updated_at,(bank_details_encrypted IS NOT NULL) AS has_bank_details,(statutory_details_encrypted IS NOT NULL) AS has_statutory_details`;await tx`INSERT INTO audit_events (actor_user_id,action,entity_type,entity_id,business_head_id,before_data,after_data,reason) VALUES (${user.id},'employee.sensitive_update','employee',${id},${employee.business_head_id},${JSON.stringify(before)}::jsonb,${JSON.stringify(rows[0])}::jsonb,${input.reason})`;return rows;});return ok(updated);}catch(error){return apiError(error);}}
